### PR TITLE
feature: adding paths operator - #2740

### PR DESCRIPTION
**Pull request by minaseem**
Link for proposal discussion - https://github.com/ramda/ramda/issues/2740

### CODE REVIEW

**Comment by minaseem** [comment]
Thank you @CrossEye for reviewing this.
If I understand correctly, below is the proposed change:

Implement `paths` natively/using internal helper functions, and then reimplement`prop` and `path` using `paths`. Please tell me whether my understanding is correct.

**Question:**
Since you said, `Ramda writes most of its object and array handling natively, without depending on other of its public functions`, I see `nth` being used in the implementation of [path](https://github.com/ramda/ramda/blob/master/source/path.js#L3). So, it is ok to use `nth` while writing `paths` natively?

**Comment by minaseem** [comment]
Hi @CrossEye 
Changes suggested by you have been completed. Please review and let me know if it ok.

PS: Apologies for the delay

**Comment by CrossEye** [comment]
This looks good to me.  Any other responses, @ramda/core?

**Comment by Bradcomp** [comment]
:bowtie: 👍

**Comment by CrossEye** [comment]
Thanks, @minaseem!

**Comment by minaseem** [comment]
Glad to be able to contribute

**Pull request merged**
