### PR TITLE
Feature/integrate ts typings

### PR DESCRIPTION
**Pull request by BjornMelgaard**
@donnut is not answering, so I decided to try myself

I have tried to use [dtslint](https://github.com/Microsoft/dtslint) instead of tslint, but ran into number of errors
Because `tests.ts` still doesn't use `$ExpectType` feature of dtslint, I've decided to do without it

In future I want to integrate number of [open pr's from DefenitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20ramda) and add missing types

### CODE REVIEW

**Comment by BjornMelgaard** [comment]
https://github.com/ramda/ramda/issues/2304
https://github.com/ramda/ramda/issues/2303

**Comment by CrossEye** [comment]
While I do think this is a good idea to have, I believe we really should get buy-in from the team that is maintaining this, and find out of they're interested in hosting this here.  

So what do you think, @mdekrey, @LiamGoodacre, @mrdziuban, @sbking, @afharo, @teves-castro, @1M0reBug, @hojberg, @charlespwd, and especially @donnut?  Should these definitions be folded into Ramda? 


I don't know the TS environment and exactly what it would mean to have this hosted here, but my biggest concern is that this becomes one more thing to update at publish time.  Do you have any suggestions  about how to make that work?  Are the tests enough?  Or are they just a start?

So I would also like to hear back from some of the core team on this.  What do you think, @raine, @davidchambers, @paldepind, @TheLudd, @buzzdecafe, @kedashoe, @Bradcomp, @scott-christopher, @asaf-romano?

**Comment by BjornMelgaard** [comment]
IMHO maintaining typings from DefinitelyTyped is hard

**Comment by CrossEye** [comment]
You see, although I've seen DefinitelyTyped, usually in response to issues here, I know nothing about it or how it fits in the TS environment.  They don't look pleasant, but I don't know how much is manual in the process.

**Comment by charlespwd** [comment]
It's pretty common for typescript users to simply add `@types/${package-name}` as a dependency in their project. 

To be honest, if Ramda isn't written in typescript, I don't see why the typings should live in here. Especially if the maintainers are not the consumers of those types.

**Comment by BjornMelgaard** [comment]
@charlespwd because as you see typings become stale and we need to do something with this

Consider `ramda-adjunct` - everyone who wants to add new feature have to change typings

**Comment by BjornMelgaard** [comment]
@CrossEye @charlespwd so what do you think?

**Comment by kedashoe** [comment]
I agree with @CrossEye , it makes more sense to host typescript stuff elsewhere. Otherwise you'll just run into the same trouble with things becoming stale, as none of the active maintainers know typescript well.

I don't know enough about DefinitelyTyped to guess why PRs there might be held up, but it does seem like the best place for it.

**Comment by BjornMelgaard** [comment]
@CrossEye @kedashoe I think you underestimate your knowledge of typescript.  

I've created fork of this [pr](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18763), and now @charlespwd is in author list and able to accept pr

I've made typings generator and hope you'll like it, and it works, but DefinitelyTyped swears at me because of unused files, maybe you'll reconsider your decision about integration typings to ramda?

**Comment by BjornMelgaard** [comment]
I would say that pr https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20177/ is ready for review if not `.gitignore` in generator dir.

If you still dont want to see typescript in this repository - ok, Its possible to remove `.gitignore` and `package.json` and left only generation script ([like it done in lodash typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/scripts/generate-modules.ts)), but I would rather not do this, because of [dependencies](https://github.com/BjornMelgaard/DefinitelyTyped/blob/2090f51a4367543e0498ecf86ac435fbfaebb0fa/types/ramda/generator/package.json) (and hooks to run generator before publishing would be very handy)

And I would rather not do this because I still think that integration is the right thing. 

> I don't know enough about DefinitelyTyped to guess why PRs there might be held up

Because authors often abandon their projects and no one wants to hold responsibility of broken things. Maintainers of DefenitelyTyped never volunteer to maintain other people typings. I know plenty of awesome prs hanging unaccepted there for eternity and will hang more because of this.

> Otherwise you'll just run into the same trouble with things becoming stale, as none of the active maintainers know typescript well

No, there are plenty of people who know typescript and want to help you, they just need help too.

I understand that you dont want an extra load, but you will kill typings for ramda.

**Comment by BjornMelgaard** [comment]
I did it all in vain. [npm-ramda](https://github.com/types/npm-ramda/) has much better typings. I wont close pr to DefenitelyTyped in case someone want to make use of it.

**Pull request closed without merging**
