### PR TITLE
docs(concat): add note about Semigroup fantasy-land spec

### PR DESCRIPTION
**Pull request by char0n**

### CODE REVIEW

**Comment by CrossEye** [comment]
I agree with the idea, but the wording is not quite correct:

> Can also concatenate two fantasy-land compatible semigroups

A semigroup is a *type*, a collection of values.  The collection of all Strings, along with String concatenation is a Semigroup.  The positive integers along with addition is a Semigroup.  But `R.concat` will not concatenate this collection of Strings with the positive integers.

Perhaps:

> Can also concatenate two members of a fantasy-land compatible semigroup.

?

**Comment by char0n** [comment]
Rewording complete.

**Comment by buzzdecafe** [comment]
:cow2:

Thanks

**Comment by CrossEye** [comment]
Thanks @char0n !

**Comment by char0n** [comment]
Np my pleasure ;]

**Pull request merged**
