### PR TITLE
Add additional example to prop.js

### PR DESCRIPTION
**Pull request by craigayre**
This PR is to add an additional example when partially applying `prop`.

I use this form the most often and thought the docs could benefit from the addition.

### CODE REVIEW

**Comment by Bradcomp** [comment]
I like the idea of using a partially applied example, but I would prefer a different example. 

`R.map(R.prop(x))` is equivalent to `R.pluck(x)`, and `R.prop('length')` is equivalent to `R.length`, so I wouldn't recommend using `prop` in a case like the above.

Do you think you could use a different example, perhaps with `compose` or something?

`R.compose(R.inc, R.prop('x'))({x: 3})   // => 4` or something to that effect?

**Comment by craigayre** [comment]
Absolutely - the example provided was a bit contrived for brevity. I'll update

**Comment by CrossEye** [comment]
With that change, this looks good to me... but not to our linter.

It's picky about trailing spaces.  Could you update one more time to fix that?

**Comment by CrossEye** [comment]
Thank you!

**Pull request merged**
