### PR TITLE
R.repeat: Add to jsdoc @see R.times

### PR DESCRIPTION
**Pull request by notarseniy**
Adding reference into documentation of R.repeat to R.times, because they do somewhat similar things and R.repeat is based on R.times

see also: #2077

### CODE REVIEW

**Comment by kedashoe** [comment]
:+1: 

Could you please also add a `@see` from `times` to `repeat` as part of this pr?

**Comment by notarseniy** [comment]
Done. @kedashoe

**Comment by notarseniy** [comment]
thanks, @kedashoe!

**Comment by kedashoe** [comment]
thank you for the PR @notarseniy :)

**Comment by notarseniy** [comment]
oh, i forgot! probably we should regenerate https://github.com/ramda/ramda.github.io? it is should be another PR or what?

**Comment by kedashoe** [comment]
No need for another PR, it will be included automatically in the next release when the docs are generated

**Comment by notarseniy** [comment]
Got it.

**Comment by CrossEye** [comment]
Thanks, @notarseniy!

**Pull request merged**
