### PR TITLE
Add propPath function

### PR DESCRIPTION
**Pull request by ryanaghdam**
I've added a new function, `propPath`, which returns a function that returns the value at the supplied path.  It is meant to complement `prop` as `assocPath` does `assoc`.

### CODE REVIEW

**Comment by asaf-romano** [comment]
Isn't this basically path without the second argument?

**Comment by ryanaghdam** [comment]
D'oh!  It is.

I've been using Ramda for almost a year and I missed that one.  I had been using `R.compose` and `R.prop`.

**Comment by asaf-romano** [comment]
We should probably cross-referenece (See ...) the two, if they're not already.

**Comment by ryanaghdam** [comment]
That's a great idea.  I'll open a pull request that does that.

**Comment by asaf-romano** [comment]
👍

**Pull request closed without merging**
