### PR TITLE
Use uglify instead of terser - this can act as smoke test against shi…

### PR DESCRIPTION
**Pull request by Andarist**
…pping es2015+ code

### CODE REVIEW

**Comment by CrossEye** [comment]
So would you suggest reverting this change post 1.0 when we will want to embrace ES2015+ ?

**Comment by Andarist** [comment]
If you plan to ship es2015+ in your main entry point (in the file pointed by "main" in package.json) then - yeah, you should revert it and minify with terser (which is uglify fork which handles es2015+)

**Comment by CrossEye** [comment]
I think this makes sense, but would love to hear from @ramda/core .

**Comment by paldepind** [comment]
Sounds very reasonable :+1:

**Comment by Bradcomp** [comment]
I see no problem here. Is there a significant difference in bundle size? I would assume not...

**Comment by Andarist** [comment]
I havent checked - there should be no difference or it should be insignificant. The sole purpose of this PR is uglify acting as a smoke test against including es2015+ syntax, not the bundle optimization.

**Comment by CrossEye** [comment]
As always, thanks @Andarist!

**Comment by Bradcomp** [comment]
I agree the smoke test is a good idea, but not if it comes at the expense of bundle size. I'd at least like to know we are still in the ballpark.

**Comment by CrossEye** [comment]
@Andarist:

That sounds like every developer ever! :smile:

**Comment by Andarist** [comment]
```
gzip -c dist/ramda.min.js | wc -c
```
terser 12574
uglify 12508

So actually its slightly better in favour of uglifyJS 😄

**Pull request merged**
