### PR TITLE
fix Duplicate declaration "add" error in example in REPL

### PR DESCRIPTION
**Pull request by aonghusonia**

### CODE REVIEW

**Comment by davidchambers** [comment]
I prefer to use `(a, b) => a + b` here. The problem with using `R.add` (or any other binary Ramda function) is that it supports both `f(a, b)` and `f(a)(b)`. Crucially, though, `R.reduce` requires the former. The lambda makes this apparent whereas `R.add` would not.

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by aonghusonia** [comment]
I have no problem with (a, b) => a + b
the problem is that R.add  has been added to the global scope on the REPL as add and the REPL is giving a duplicate declaration error. How about:

var plus = (a, b) => a + b

**Comment by buzzdecafe** [comment]
`plus` is fine with me

**Comment by CrossEye** [comment]
`:plus1:` on `plus`.

**Comment by buzzdecafe** [comment]
thanks

**Pull request merged**
