### PR TITLE
feat: add memoizeLRUWith

### PR DESCRIPTION
**Pull request by Qquanwei**
Resolve memoizeWith in memory sensetive situation.

## Before
will be bring memory leak.

```javascript
function aBigObject() {
  return {}; 
}

var fn = memoizeWith(R.identity, aBigObject);

fn(1);
fn(2);
...
```

## After

always hold 100 items in memory.
```javascript
function aBigObject() {
  return {}; 
}

var fn = memoizeLRUWith(100, R.identity, aBigObject);

fn(1);
fn(2);
...
```

### CODE REVIEW

**Comment by Qquanwei** [comment]
Or using inject cache strategy `memoizeBy(new LRU(100), identity, fn)` maybe better ?

**Comment by CrossEye** [comment]
At a first read-through, this looks like very well-written, easily maintainable code.  Kudos.  If we decide to go this way, we can investigate further the decision about using an injectible caching strategy.

But I'm not particularly convinced that this is a good fit for Ramda.  I teeter even on `memoizeWith`.  Ramda generally avoids maintaining any internal state; memoization inherently involves state.  Granted the state is not observable, except perhaps by timing calls to the cache.  But it's still state, and that feels off to me.  If we didn't have it from our early days, we probably wouldn't add it now.  This PR adds even more state management.  That bothers me.

On the other hand, this is an undeniably useful function and it's non-trivial to write oneself -- two factors that help us decide whether to include something in Ramda.

I'd love to hear more from you, @Qquanwei about why you think this is a good idea.

And I'd love to hear thoughts from @kudorori, @Izhaki, @meszaros-lajos-gyorgy, who participated in #2509 and of course from others interested, especially @ramda/core.  Is this something we want to add to Ramda.  Also @char0n: if this isn't something Ramda wants to take on, do you think ramda-adjunct might be interested?

**Comment by Qquanwei** [comment]
In practice, pure functions tend to work well with memory functions, so a memory function with state is essential for Ramda.I often use the memoizeWith function in some optimization scenarios, but it can cause problems due to memory leaks. #2509 is a good solution but it lacks sufficient intelligence, so I would like to provide a convenient caching strategy so we have more options for performance optimization.This PR was not a deliberate choice, I would prefer a lodash like Memoize function that allows for cache policy injection.

**Comment by char0n** [comment]
> Also @char0n: if this isn't something Ramda wants to take on, do you think ramda-adjunct might be interested?

@CrossEye, @Qquanwei although in [ramda-adjunct](https://github.com/char0n/ramda-adjunct) we adhere to same general principles as ramda, our bar is lower and function like `memoize` would be acceptable. But it would need to be as flexible as the one provided by lodash with resolver, full cache controll and policy injection.

**Comment by CrossEye** [comment]
So I had never looked at the lodash `memoize` function.  This is the current description.  

> `_.memoize(func, [resolver])`
> 
> Creates a function that memoizes the result of `func`. If `resolver` is provided, it determines the cache key for storing the result based on the arguments provided to the memoized function. By default, the first argument provided to the memoized function is used as the map cache key. The `func` is invoked with the `this` binding of the memoized function.
> 
> **Note**: The `cache` is exposed as the cache property on the memoized function. Its creation may be customized by replacing the `_.memoize.Cache` constructor with one whose instances implement the [Map][ma] method interface of `clear`, `delete`, `get`, `has`, and `set`.

There is definitely something in there to like.  If Ramda was to take this on, I think hanging the `cache` property off the generated function would make sense for us, and probably reusing the `Map` interface would also make sense.  (I wouldn't use a constructor but a plain function; but that's minor.)   I would keep with our explicit equivalent of `resolver`, and I would make the cache strategy a required parameter; certainly I wouldn't add the global state of `_memoize.Cache` used in lodash.  We could retain backward compatibility in `memoizeWith` as the partial application of the current strategy to a new `memoize` function.

This is still not to say that I'm sure we want to do so.

But if we do, I can see writing it this way, keeping our current `memoizeWith` for backward compatibility, but simply implementing it as `const memoizeWith = memoize(_currentNaiveCacheStrategy)`, so that now `memoizeWith.cache` has the `Map` instance interface.  (Not that `clear` or `delete` would do anything in the current strategy.)

I'm still slightly queasy about the notion, though.  Perhaps it's no big deal, as it's not Ramda offering a stateful tool, only allowing users to bring their own along.  But it's still an odd direction for Ramda.

I'd still really like to hear from others.  @buzzdecafe?  @Bradcomp? @davidchambers? 

  [ma]: http://ecma-international.org/ecma-262/7.0/#sec-properties-of-the-map-prototype-object

**Comment by davidchambers** [comment]
One option is to suggest that people use [lodash.memoize][1].


[1]: https://www.npmjs.com/package/lodash.memoize

**Pull request closed without merging**
