### PR TITLE
docs: improve usability

### PR DESCRIPTION
**Pull request by raine**
- focus filter input automatically
- go to the first entry on Enter

### CODE REVIEW

**Comment by CrossEye** [comment]
:herb:

**Comment by raine** [comment]
there we go

**Comment by CrossEye** [comment]
LGTM. Anyone else have comments?

**Comment by buzzdecafe** [comment]
:cow2:

A related question: rather than including `dist/ramda.js` should we point at version on CDN?

**Comment by raine** [comment]
Ramda is included also for the purpose of making it available for users in the dev tools REPL.

It's a bit of a corner case, but there might be a situation where the page documents certain API that isn't available in the version we are using from cdn.

**Comment by buzzdecafe** [comment]
I think the only times referencing the latest tag from a CDN would be a problem are:

* when generating docs from HEAD; or
* in the interval between publishing a new version & its docs and the CDN getting updated.

as i said, this is a separate issue. This PR is good to go as is AFAICT

**Comment by CrossEye** [comment]
The docs are still built against `dist/ramda.js`, not the `src` dir, correct?  So we need to build it as part of creating the docs.  But we definitely shouldn't be _using_ it.

**Pull request merged**
