### PR TITLE
clean up root dir, closes #802

### LINKED ISSUE #802: clean up root dir
proposed:

Move:

* docs/
* jsdoc-template/
* less/
 
under lib/doc

Move:

* sauce 

under lib/

Move:

* tasks/

under lib/grunt

Move 

* bench/

under lib/

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by davidchambers** [comment]
I imagine you need to update __.gitignore__ and __.npmignore__.

**Comment by buzzdecafe** [comment]
good point

**Comment by CrossEye** [comment]
:herb:

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
The only question now, given #800, is whether this should be done in 0.10.x or should wait for 0.11.0.

Any thoughts?

**Comment by davidchambers** [comment]
#817 alone warrants a minor release if accepted, so we might release 0.11.0 quite soon. :)

**Pull request merged**
