### PR TITLE
add hasPath

### PR DESCRIPTION
**Pull request by vitalets**
As discussed in #2499 here is a proposal for `hasPath` function. 

Notes:
1. only own properties are checked
2. imho `hasPathIn` should not be implemented right now (until somebody will come with the request)

### CODE REVIEW

**Comment by CrossEye** [comment]
This looks great.  And I agree about `hasPathIn`.  Does anyone disagree?  @ramda/core?

One thing I would like to add, though, is to reimplement `has` in terms of this.  (`curry2(function has(prop, obj) {return hasPath([prop], obj);}`) That way these two functions cannot get out of sync.

**Comment by vitalets** [comment]
> is to reimplement `has`

Great, will do.

One more thing I'd like to point attention: currently `hasPath()` with zero-length path returns false. Similar to `has()` with empty string. But `path()` with empty path argument returns object itself. Is it ok?
```js
hasPath([], {x: 'foo'}); // => false
path([], {x: 'foo'});    // => {x: 'foo'}
```

**Comment by CrossEye** [comment]
This looks very good to me.  I think this is quite a useful little function.

**Comment by vitalets** [comment]
Thank you! 👍

**Pull request merged**
