### PR TITLE
Improve comments around lens functions

### PR DESCRIPTION
**Pull request by scott-christopher**
In response to #1585, this change adds some more descriptive argument names along with some code comments around the various lens functions.

### CODE REVIEW

**Comment by CrossEye** [comment]
:herb:

This looks great!  I'm not generally a fan of source-code comments, but this material is difficult enough to warrant them.

**Comment by davidchambers** [comment]
:deciduous_tree: I *wrote* this code yet I very much appreciate these comments!

**Comment by Sequoia** [comment]
:palm_tree: +1 to the comments & descriptive names! I still don't fully grok lenses, but this might help make it easier :smile_cat: 

One style question: why are `Const` and `Ident` capitalized? In Javascript there is a very strong convention of capitalizing only "constructor" functions, i.e. it signals that the function should be called with `new MyConstructor`. Speaking as someone from the JS world rather than FP world, I can confidently say that this is likely to cause at least confusion for some people.

**Comment by jackfirth** [comment]
@Sequoia In the FP JS world, type constructors are meant to be normal functions - you should never need to call anything with `new`. Shoving functions that require `new` to call them into `compose` chains for example, is quite annoying and bug prone. In Ramda specifically, capitalized functions are usually constructors for things that implement the Javascript equivalent of Haskell's typeclasses (I think). For instance, `Const` and `Ident` specifically refer to the `Const` and `Identity` types from Haskell, which are both examples of very simple Functors. In Javascript and in Ramda, typeclasses are [defined in terms of the Fantasy Land spec](https://github.com/fantasyland/fantasy-land).

Disclaimer: I am but a humble lurker, and many more knowledgeable people than me can contribute better explanations than this.

**Comment by davidchambers** [comment]
> Disclaimer: I am but a humble lurker, and many more knowledgeable people than me can contribute better explanations than this.

The comments you have posted recently have been excellent! You undersell yourself (which I appreciate, as a New Zealander).

To add one point to @jackfirth's comment, the names `id`/`identity` and `const`/`constant` are commonly given to functions quite different from those in question:

```haskell
id :: a -> a
const :: a -> b -> a
```

In this case, we have:

```haskell
Identity :: a -> Identity a
Const :: a -> Const a
```

`Identity` is a constructor (in the Haskell sense) for an Identity value. In Haskell, data constructors must be capitalized. There's no such requirement in JavaScript, but it's convenient to be able to define both `Identity` and `identity` so we've adopted the Haskell approach as a convention.

**Comment by Sequoia** [comment]
Fair enough!

**Pull request merged**
