### PR TITLE
package.json: attempt to fix erroneous `npm test` failures

### PR DESCRIPTION
**Pull request by davidchambers**
See, for example, <https://travis-ci.org/ramda/ramda/jobs/57303350>.

### CODE REVIEW

**Comment by CrossEye** [comment]
I don't see how this would help anything.  The Grunt script [already does this][gr] internally.


  [gr]: https://github.com/ramda/ramda/blob/master/Gruntfile.js#L213

**Comment by davidchambers** [comment]
> I don't see how this would help anything.

Running four commands in series is different from running one command which does four things. I don't know *why* this change fixes the problem for me, but the problem was causing lots of pull requests to fail. I'm happy to rely on empirical evidence in this case.

**Comment by CrossEye** [comment]
I have no problem using it if it does fix things.  I just didn't know if it was a magical incantation or if you'd run down the source of the problem.

**Comment by davidchambers** [comment]
Definitely a magical incantation. :frog:

**Comment by CrossEye** [comment]
The really odd thing is that as far as I can tell, this should be making us run jshint, jscs, and browserify each twice, but that doesn't seem to be happening...  I wish I understood magic.

**Comment by TheLudd** [comment]
I have noticed one thing and I don't know if it is related but grunt-cli is installed globally. I think it would be better if it was added as a devDependency. Then anyone could use grunt in the npm scripts after doing npm install. I have previously seen conflicts between global and local modules. But agan, not sure that is the case here.

**Comment by buzzdecafe** [comment]
in that case the solution is to drop grunt

**Pull request merged**
