### PR TITLE
Update documentation for Deno import

### PR DESCRIPTION
**Pull request by sebastienfilion**

### CODE REVIEW

**Comment by hitmands** [comment]
relates to: 
 - https://github.com/ramda/ramda/pull/3054
 - https://github.com/ramda/ramda/pull/3042

**Comment by hitmands** [comment]
Hi @sebastienfilion, 
Pr looks straightforward to mee.

I'd only ask to provide further description to help readers understand the context and use cases.

**Comment by sebastienfilion** [comment]
> I'd only ask to provide further description to help readers understand the context and use cases.

What kind of information do you think is pertinent? Like a link to Deno? I didn’t want to make this part of the document look too heavy.

**Comment by CrossEye** [comment]
Yes, maybe just if the word "Deno" is a link to the Deno page, then anyone who doesn't know what it is can follow it to there.

**Pull request merged**
