### PR TITLE
Add `.js` extension to source files

### PR DESCRIPTION
**Pull request by sebastienfilion**
Omitting the file extension when importing a module is a quirk of the NodeJS' require importing method and should be discouraged -- As standard ES module is getting ground (Browser import, Deno import).

Resolve: https://github.com/ramda/ramda/issues/3028

### CODE REVIEW

**Comment by sebastienfilion** [comment]
Should I commit the rebuilt distribution file?

**Comment by Bradcomp** [comment]
You don't need to commit the dist file https://github.com/ramda/ramda/blob/master/CONTRIBUTING.md

**Comment by sebastienfilion** [comment]
@Bradcomp I added a plugin to enforce file extension on import, but Codeclimate is complaining although I tested it locally -- Is it possible that they don't support ESLint plugins? If that's the case, what's your preferred way to handle this?

**Comment by CrossEye** [comment]
pinging @hitmands: Do you have any experience with this?  I'm still very new to Code Climate.

**Comment by hitmands** [comment]
Need to take a look into this,
We might need to disable codeclimate.eslint if this plugin isn’t supported

**Comment by hitmands** [comment]
It seems that (unless differently specified) [`eslint-3` is used by default](https://docs.codeclimate.com/docs/eslint), while this repo is using [`esling@5`](https://github.com/ramda/ramda/blob/master/package.json#L100).

I'd suggest to set `channel-5` [here](https://github.com/ramda/ramda/blob/master/.codeclimate.yml#L19), 
image


- https://docs.codeclimate.com/docs/eslint

______

My initial thoughts are that the version of `plugins/import` available for `eslint@3` didn't have any `ignorePackages` option.

image

> Is it possible that they don't support ESLint plugins?

@sebastienfilion it seems that the plugin is supported, 
but the specific config `ignorePackages` isn't.

- https://codeclimate.com/github/ramda/ramda/pull/3042

**Comment by sebastienfilion** [comment]
Thanks for all the help; I've switched the setting from `ignorePackages` to `always` -- it works for my purpose because the source files are self-dependent. Let me know what you think.

**Comment by sebastienfilion** [comment]
If you guys are okay, I'm gonna prepare a PR on the Deno "database" to add Ramda as an official third-party!?

**Comment by Bradcomp** [comment]
@sebastienfilion I have no problem with that, however typescript compatibility isn't a priority for the library, and there is at least one function we have that is a syntax error (`R.type`).

**Comment by CrossEye** [comment]
@sebastienfilion: Absolutely.  Go for it!

**Comment by sebastienfilion** [comment]
@Bradcomp i will mention it on the PR; but I don’t think that FP users care much about typed-languages. We’ll see what Ryan says.

**Comment by sebastienfilion** [comment]
For those that are interested: I submitted Ramda as Deno third-party. https://github.com/denoland/deno_website2/pull/1174

**Pull request merged**
