### PR TITLE
It must be `sets`

### PR DESCRIPTION
**Pull request by hemanth**
Was just reading the source and noticed this small glitch.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
nice catch, thanks.

**Comment by hemanth** [comment]
:+1: Planning to contribute something bigger to this project.

 BTW heavily influenced by ramda started something small along with @stoeffel [fp-dom](https://github.com/fp-dom) and [fp-js](https://github.com/fp-js) would love to hear your feedback! (: 

[ /me takes advantage of this PR (;]

**Comment by buzzdecafe** [comment]
i noticed the fp-dom projects, looks like a great idea to me, i'll be interested to see how they progress. 

This PR is failing at present because we unfortunately require you to run `make test lint` and check in the built dist artifact as well. Hoping to fix that presently (ping @CrossEye)

**Comment by stoeffel** [comment]
>  noticed the fp-dom projects, looks like a great idea to me

@buzzdecafe Thanks :smile:

**Comment by hemanth** [comment]
> i'll be interested to see how they progress.

That's a booster, thank you! :smile: 

Yeah, this PR can't break the build, NP.

**Comment by CrossEye** [comment]
Yeah, yeah, I'm piling up the work at this point.  :frowning:

**Comment by buzzdecafe** [comment]
:bus:

**Comment by davidchambers** [comment]
Closed via 59bf8fbbfd1dd8fa13966cc43911d898b26d1cf3

**Comment by hemanth** [comment]
Thanks @davidchambers :+1:

**Pull request closed without merging**
