### PR TITLE
remove functions deprecated in v0.14.0

### PR DESCRIPTION
**Pull request by davidchambers**
I'm sad to see `R.isNaN` go. :cry:

### CODE REVIEW

**Comment by CrossEye** [comment]
I don't even remember the deprecation of `mean` and `median`... although I remember when they were added and didn't see them as crucial at the time...

**Comment by davidchambers** [comment]
This pull request only removes `R.isNaN`. Several files made use of this function, so this pull request replaces occurrences of `R.isNaN` with `R.identical(NaN)`.

**Comment by CrossEye** [comment]
Yeah, I had a weird afternoon with GitHub.  A number of pages were jumbled.  I seemed to have misread a number of things, on Ramda and several other projects.  Sorry about that.

**Comment by davidchambers** [comment]
`:herb:`?

**Comment by CrossEye** [comment]
Oh, yes, and :herb:

Sorry, got distracted.  Really gotta find me a new emoji, too.  :smile:

**Pull request merged**
