### PR TITLE
Fixed JSDocs

### LINKED ISSUE #2328: `toString` & `contains` dist API has something wrong
`toString` becomes `toString$1`
`contains` becomes `contains$1`

screen shot 2017-10-11 at 11 21 37 pm

### PR DESCRIPTION
**Pull request by Andarist**
Fixes #2328

With this PR and ramda/ramda.github.io#200 merged in, new documentation builds should be ok.

### CODE REVIEW

**Comment by kedashoe** [comment]
We actually received a PR for `keys` and `trim`, #2327, it just hadn't been merged yet. Would you like to update this PR with just your change to `__`?

**Comment by Andarist** [comment]
Done.

**Comment by cht8687** [comment]
what will this change fix? I've tried to use this branch to build a new version and used in ramda.github.io project and didn't see any changes in generated result related to this change.

**Comment by Andarist** [comment]
Its a joined with the PR to ramda.github.io repo (its linked to this thread). Probably the docs gonna be based on src directory, rather than on umd build. And when that happens this PR needs to be merged to fix the new way of building the docs

**Pull request merged**
