### PR TITLE
remove package-lock.json

### PR DESCRIPTION
**Pull request by davidchambers**
It does not make sense for a library to use a lockfile.

### CODE REVIEW

**Review by customcommander — APPROVED** [review]
I don't object to this at all but we need to be aware that any dependencies or transitive dependencies can be compromised with malwares targeting developers & CI/CD machines. I think that the `package-lock.json` file along with the appropriate install flags has its role in trying to mitigate those issues.

I have to say that I don't quite see how this is a prerequisite to making a `v0.27` release. 

I'm approving this anyway assuming you know what's best.

**Comment by customcommander** [comment]
@davidchambers Would you like to merge this PR?

**Comment by adispring** [comment]
Due to recently colors npm event: https://github.com/Marak/colors.js/issues/285, I think it's better not remove package lock file. The devDependencies maybe be injected with malware.

We can trust package lock file, but not package.json.

**Comment by PythonCoderAS** [comment]
The package lock file isn't published. It should be consumed by CI to always install an exact working copy.

**Comment by imcotton** [comment]
Currently this repo have a one year old (Jan 26, 2021) lock file with `50 vulnerabilities (23 moderate, 18 high, 9 critical)`[^1] during `npm ci`, I would choose to have no lock file in exchange with up to dated mitigation.

[^1]: https://github.com/ramda/ramda/runs/4748752673?check_suite_focus=true#step:3:91

**Comment by imcotton** [comment]
And no, the **Dependabot** automation have no difference with no lock file, it only produces spamming commits and bulky objects.

**Comment by PythonCoderAS** [comment]
> Currently this repo have a one year old (Jan 26, 2021) lock file with `50 vulnerabilities (23 moderate, 18 high, 9 critical)`[1](#user-content-fn-1-163c5e569d8199af19bcd68603f327c2) during `npm ci`, I would choose to have no lock file in exchange with up to dated mitigation.
> 
> ## Footnotes
> 1. https://github.com/ramda/ramda/runs/4748752673?check_suite_focus=true#step:3:91 [↩](#user-content-fnref-1-163c5e569d8199af19bcd68603f327c2)

The solution should be to remake the lockfile not delete it entirely.

**Comment by imcotton** [comment]
With thousands of indirect dependencies from `node_modules`, what's the best strategy off to remake & commit lockfile effectively?

**Pull request closed without merging**
