### PR TITLE
add isNotNil function to check value for not null or not undefined

### PR DESCRIPTION
**Pull request by anandsahil**
1. Allows checking for not null or not undefined , so that we do not need to always negate isNil .

### CODE REVIEW

**Comment by davidchambers** [comment]
`x => x != null` seems quite reasonable to me. I'm not *strongly* opposed to adding this function, though. ;)

**Comment by CrossEye** [comment]
I feel the same.  No major objection, but it's so easy to add yourself, and can be done as a simple arrow or as `complement(isNil)` that I see little need.

**Comment by buzzdecafe** [comment]
i agree with @davidchambers . if you want to avoid the lambda for some reason, you could also `complement(isNil)`

**Comment by anandsahil** [comment]
i agree but i feel that always , abstracting it in ramda would be good and to enjoy the functional and currying native features for free.

it would be really nice to have it

**Pull request closed without merging**
