### PR TITLE
Replace * with Any in all type signatures

### PR DESCRIPTION
**Pull request by svozza**
This was discussed in #1554 and seemed to have a reasonable bit of support. I'm happy to do some of the other suggestions made in that issue, like a consistent way to represent dictionaries - as `{a}` - but that seemed to get a more lukewarm reception.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
LGTM

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
I think the point that @joneshf make [on Gitter][gi] is pretty relevant.  Many of our uses of `*` should not actually be replaced with `Any` but with a simple type variable.  `Any` is mostly useful for the construct `[Any]` to cover such monstrosities that JS allows as `['abc', 42, false, {}, new Date()]`

For instance, `tap` should just be

```haskell
tap:: (a -> b) -> a -> a
```

Yes, `b` is an unknown type, but it's fixed for a particular invocation of `tap` so it might as well be represented by a simple type variable such as `a`, `b`, `c`, etc.

That the type is irrelevant and simply discarded is evident from the signature.  We don't need a token such as `*` or `Any` to tell us that.

  [gi]: https://gitter.im/ramda/ramda?at=56a5047084cccde9258ae6b3

**Comment by svozza** [comment]
Fair enough, if I can get a steer on what functions will require the `Any` type then I can update the ones that don't with simple type variables.

**Comment by CrossEye** [comment]
Dropped and forgotten ages ago.  This may still be worth doing, but the library has moved too far to use this implementation.

**Pull request closed without merging**
