### PR TITLE
remove _has

### PR DESCRIPTION
**Pull request by davidchambers**

### CODE REVIEW

**Comment by davidchambers** [comment]
I take it you're against this change, @CrossEye? Feel free to close this pull request if so.

**Comment by CrossEye** [comment]
I think I missed it in the flurry.   I will look at it later in the day.

**Comment by davidchambers** [comment]
((:bell:)) @CrossEye

**Comment by buzzdecafe** [comment]
> I will look at it later in the day.

really gotta pin down *which* day

**Comment by CrossEye** [comment]
Every day.  

Wow!  I don't even remember making that comment.  I don't have any major objection, although it seems to be adding duplication to our code.

Why not this?

    // internal/_hasOwn.js:
    module.exports = Object.prototype.hasOwnProperty;
    // ...
    // another file:
    var _hasOwn = require('./internal/_hasOwn')
    // ...
    if (_hasOwn.call(prop, obj)) { ... }

**Comment by davidchambers** [comment]
My goal is to reduce the overhead of including Ramda functions à la carte in a web application. Consider the following "app":

```javascript
var merge = require('ramda/src/merge');

console.log(merge({a: 1, b: 1}, {b: 2, c: 2}));
```

What might this look like once packaged?

```console
$ node_modules/.bin/cjsify app.js
// Generated by CommonJS Everywhere 0.9.7
(function (global) {
  function require(file, parentModule) {
    if ({}.hasOwnProperty.call(require.cache, file))
      return require.cache[file];
    var resolved = require.resolve(file);
    if (!resolved)
      throw new Error('Failed to resolve module ' + file);
    var module$ = {
        id: file,
        require: require,
        filename: file,
        exports: {},
        loaded: false,
        parent: parentModule,
        children: []
      };
    if (parentModule)
      parentModule.children.push(module$);
    var dirname = file.slice(0, file.lastIndexOf('/') + 1);
    require.cache[file] = module$.exports;
    resolved.call(module$.exports, module$, module$.exports, dirname, file);
    module$.loaded = true;
    return require.cache[file] = module$.exports;
  }
  require.modules = {};
  require.cache = {};
  require.resolve = function (file) {
    return {}.hasOwnProperty.call(require.modules, file) ? require.modules[file] : void 0;
  };
  require.define = function (file, fn) {
    require.modules[file] = fn;
  };
  var process = function () {
      var cwd = '/';
      return {
        title: 'browser',
        version: 'v0.12.0',
        browser: true,
        env: {},
        argv: [],
        nextTick: global.setImmediate || function (fn) {
          setTimeout(fn, 0);
        },
        cwd: function () {
          return cwd;
        },
        chdir: function (dir) {
          cwd = dir;
        }
      };
    }();
  require.define('/app.js', function (module, exports, __dirname, __filename) {
    var merge = require('/node_modules/ramda/src/merge.js', module);
    console.log(merge({
      a: 1,
      b: 1
    }, {
      b: 2,
      c: 2
    }));
  });
  require.define('/node_modules/ramda/src/merge.js', function (module, exports, __dirname, __filename) {
    var _curry2 = require('/node_modules/ramda/src/internal/_curry2.js', module);
    var _extend = require('/node_modules/ramda/src/internal/_extend.js', module);
    module.exports = _curry2(function merge(a, b) {
      return _extend(_extend({}, a), b);
    });
  });
  require.define('/node_modules/ramda/src/internal/_extend.js', function (module, exports, __dirname, __filename) {
    var keys = require('/node_modules/ramda/src/keys.js', module);
    module.exports = function _extend(destination, other) {
      var props = keys(other), idx = -1, length = props.length;
      while (++idx < length) {
        destination[props[idx]] = other[props[idx]];
      }
      return destination;
    };
  });
  require.define('/node_modules/ramda/src/keys.js', function (module, exports, __dirname, __filename) {
    var _contains = require('/node_modules/ramda/src/internal/_contains.js', module);
    var _curry1 = require('/node_modules/ramda/src/internal/_curry1.js', module);
    var _has = require('/node_modules/ramda/src/internal/_has.js', module);
    module.exports = function () {
      var hasEnumBug = !{ toString: null }.propertyIsEnumerable('toString');
      var nonEnumerableProps = [
          'constructor',
          'valueOf',
          'isPrototypeOf',
          'toString',
          'propertyIsEnumerable',
          'hasOwnProperty',
          'toLocaleString'
        ];
      return _curry1(function keys(obj) {
        if (Object(obj) !== obj) {
          return [];
        }
        if (Object.keys) {
          return Object.keys(obj);
        }
        var prop, ks = [], nIdx;
        for (prop in obj) {
          if (_has(prop, obj)) {
            ks[ks.length] = prop;
          }
        }
        if (hasEnumBug) {
          nIdx = nonEnumerableProps.length;
          while (nIdx--) {
            prop = nonEnumerableProps[nIdx];
            if (_has(prop, obj) && !_contains(prop, ks)) {
              ks[ks.length] = prop;
            }
          }
        }
        return ks;
      });
    }();
  });
  require.define('/node_modules/ramda/src/internal/_has.js', function (module, exports, __dirname, __filename) {
    module.exports = function _has(prop, obj) {
      return Object.prototype.hasOwnProperty.call(obj, prop);
    };
  });
  require.define('/node_modules/ramda/src/internal/_curry1.js', function (module, exports, __dirname, __filename) {
    var __ = require('/node_modules/ramda/src/__.js', module);
    module.exports = function _curry1(fn) {
      return function f1(a) {
        if (arguments.length === 0) {
          return f1;
        } else if (a === __) {
          return f1;
        } else {
          return fn(a);
        }
      };
    };
  });
  require.define('/node_modules/ramda/src/__.js', function (module, exports, __dirname, __filename) {
    module.exports = { ramda: 'placeholder' };
  });
  require.define('/node_modules/ramda/src/internal/_contains.js', function (module, exports, __dirname, __filename) {
    var _indexOf = require('/node_modules/ramda/src/internal/_indexOf.js', module);
    module.exports = function _contains(a, list) {
      return _indexOf(list, a) >= 0;
    };
  });
  require.define('/node_modules/ramda/src/internal/_indexOf.js', function (module, exports, __dirname, __filename) {
    module.exports = function _indexOf(list, item, from) {
      var idx = 0, len = list.length;
      if (typeof from == 'number') {
        idx = from < 0 ? Math.max(0, len + from) : from;
      }
      while (idx < len) {
        if (list[idx] === item) {
          return idx;
        }
        ++idx;
      }
      return -1;
    };
  });
  require.define('/node_modules/ramda/src/internal/_curry2.js', function (module, exports, __dirname, __filename) {
    var __ = require('/node_modules/ramda/src/__.js', module);
    var _curry1 = require('/node_modules/ramda/src/internal/_curry1.js', module);
    module.exports = function _curry2(fn) {
      return function f2(a, b) {
        var n = arguments.length;
        if (n === 0) {
          return f2;
        } else if (n === 1 && a === __) {
          return f2;
        } else if (n === 1) {
          return _curry1(function (b) {
            return fn(a, b);
          });
        } else if (n === 2 && a === __ && b === __) {
          return f2;
        } else if (n === 2 && a === __) {
          return _curry1(function (a) {
            return fn(a, b);
          });
        } else if (n === 2 && b === __) {
          return _curry1(function (b) {
            return fn(a, b);
          });
        } else {
          return fn(a, b);
        }
      };
    };
  });
  require('/app.js');
}.call(this, this));
```

A certain amount of boilerplate is unavoidable, and this would compress well, but I still see value in taking small steps to simplify our internal dependency graph where it is relatively painless to do so.

**Comment by CrossEye** [comment]
> My goal is to reduce the overhead of including Ramda functions à la carte in a web application.

While that's a useful goal, I wouldn't want to put that ahead of other, more central, ideas of the project.  When it adds duplication to the code-base it worries me.  My guess is that the  _à la carte_ usage will be a significantly smaller part of our audience, at least for a while, than the _à prix fixe_ version.  So I wouldn't want to harm the latter much in order to make the former easier.

I _do_ want to remove our dependence on `internal` as much as possible.  But that's mostly a feeling of wanting to dogfood our stuff. I really don't have a problem with some dependency trees so long as they don't grow terribly deep.

**Comment by davidchambers** [comment]
It's your call, @CrossEye. Let's merge this pull request or close it.

**Comment by megawac** [comment]
I'd say make `_has` just be `_has = Object.prototype.hasOwnProperty` then do `_has.call(obj, prop)` everywhere. :-1:  for the current way

**Comment by CrossEye** [comment]
@megawac: :+1:

I don't know if we should update this PR or introduce another one, though.

**Comment by davidchambers** [comment]
> I don't know if we should update this PR or introduce another one, though.

It should be a new pull request.

`_has` shouldn't be an :alien: for `Object.prototype.hasOwnProperty`. According to convention one would expect `_has` to take its arguments in the same order as `R.has`, as it currently does. The :alien: should be named `_hasOwnProperty` instead.

To summarize, there are three approaches:

```javascript
var _has = require('./internal/_has');

... _has(prop, obj) ...
```

```javascript
... Object.prototype.hasOwnProperty.call(obj, prop) ...
```

```javascript
var _hasOwnProperty = require('./internal/_hasOwnProperty');

... _hasOwnProperty.call(obj, prop) ...
```

My understanding is you're proposing the third approach. Why, out of interest? Just to avoid two property accesses incurred in evaluating `Object.prototype.hasOwnProperty`?

**Comment by CrossEye** [comment]
[Earlier in this discussion][ss], I suggested this

```javascript
var _hasOwn = require('./internal/_hasOwn');

... _hasOwn.call(obj, prop) ...
```

The suggestion from @megawac was similar enough that I just :+1:'d it, although I prefer the name `_hasOwn` to `_has` (or to `_hasOwnProperty`.)

> My understanding is you're proposing the third approach. Why, out of interest? Just to avoid two property accesses incurred in evaluating `Object.prototype.hasOwnProperty`?

That, and to write more readable code.  I don't really have an issue with the current `has` function, but if we're going to remove it, having the duplicated calls to `Object.prototype.hasOwnProperty.call(...)` littering our codebase would bother me some.  That's all.

  [ss]: https://github.com/ramda/ramda/pull/889#issuecomment-82375368

**Comment by davidchambers** [comment]
Gotcha. Thanks.

**Pull request closed without merging**
