### PR TITLE
 Fix duplicate declaration errors in converge example in REPL

### PR DESCRIPTION
**Pull request by aonghusonia**
When you run the converge example in the ramda REPL you get a duplicate declaration error for the add, subtract & multiply functions

### CODE REVIEW

**Comment by davidchambers** [comment]
Thanks, @aonghusonia. What do you think about using `R.add` and friends in the example, to save us from redefining these functions?

**Comment by aonghusonia** [comment]
that would be the simplest solution but I did not know if add, subtract & multiply had been defined for some illustrative purpose similarly to the reduce example https://github.com/ramda/ramda/pull/1777.
 If not I agree example could simply read:

//≅ R.multiply( R.add(1, 2), R.subtract(1, 2) );
R.converge(R.multiply, [R.add, R.subtract])(1, 2); //=> -3

var add3 = (a, b, c) => a + b + c;
R.converge(add3, [R.multiply, R.add, R.subtract])(1, 2); //=> 4

**Comment by davidchambers** [comment]
Someone recently suggested moving away from arithmetic examples. This is sensible, I think. How about something like this instead?

```javascript
> R.converge((a, b, c) => a + b + c, [R.toUpper, R.toLower, R.identity])('Ramda')
'RAMDAramdaRamda'
```

Using `converge` with binary functions is pretty hard to imagine in real code. I think a single example featuring an array of unary functions (such as the one above) would suffice.

**Comment by aonghusonia** [comment]
how about:

**Comment by aonghusonia** [comment]
how about: 

var capitalizeFirst = R.converge(R.concat, [R.compose(R.toUpper, R.head), R.tail]);

capitalizeFirst("converge a list of branching functions"); //=>"Converge a list of branching functions"

**Comment by davidchambers** [comment]
That's another option. It's certainly a more realistic example. The only problem is that it's more simply expressed without `converge`:

```javascript
//    capitalizeFirst :: String -> String
const capitalizeFirst = R.replace(/./, R.toUpper);
```

**Comment by aonghusonia** [comment]
Courtesy of [tacit Ramda](https://medium.com/@bobiblazeski/tacit-ramda-c914775ff4b1#.n2t5osovn) :

```javascript
var avg = R.converge(R.divide,[R.sum,R.length])
avg([1,2,3,4,5,6,7])//=> 4

//or

var isDuplicate  = R.converge(R.complement(R.equals),[R.indexOf,R.lastIndexOf]);
isDuplicate(2,[2,1,3,1,6]) //=> False
isDuplicate(1,[2,1,3,1,6]) //=> true
```

I'm leaning towards avg as a simple but realistic example but you can still do it more simply as:
avg = lift(divide)(sum,length)

**Comment by davidchambers** [comment]
I like the `avg` example. :)

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
I'm still catching up on everything.  This is a very nice improvement, thanks!

I would offer a caveat.  If we get around to it, it would be slightly clearer still with this variant:

```js
avg([1, 2, 3, 4, 5, 6]); //=> 3.5
```

which makes it very explicit *which* average we're discussing.  (That is mean, not median or mode.)

But this is far from critical.

**Pull request merged**
