### PR TITLE
use op-style currying for R.has

### PR DESCRIPTION
**Pull request by davidchambers**

### CODE REVIEW

**Comment by davidchambers** [comment]
Any objections? :)

**Comment by buzzdecafe** [comment]
have you benched it? I'm curious to see what it costs

**Comment by davidchambers** [comment]
> have you benched it? I'm curious to see what it costs

There's no cost as we're using uncurried `_has` internally.

**Comment by buzzdecafe** [comment]
i think i responded to the wrong pr

**Comment by davidchambers** [comment]
Does anyone object to merging this pull request? I'd like to pull in these changes regardless of what happens with #817 as there's value in having an uncurried version of such an important function.

**Comment by buzzdecafe** [comment]
do it

:cow2:

**Pull request merged**
