### PR TITLE
Provide babel-plugin-ramda example, clarify docs.

### PR DESCRIPTION
**Pull request by AndrewSouthpaw**
Related to #2441, this PR provides an example config file for usage of `babel-plugin-ramda` and improves language to read a bit more easily.

### CODE REVIEW

**Comment by JasonSooter** [comment]
@AndrewSouthpaw Should we change Rollbar to Rollup while we're editing here?

**Comment by CrossEye** [comment]
> Should we change Rollbar to Rollup while we're editing here?

I just assumed that I hadn't noticed the latest and greatest tool that had been released.  :smile:

**Comment by JasonSooter** [comment]
Well, if I didn't use the Rollbar JS Error Tracking software, I might have thought the same.

**Comment by AndrewSouthpaw** [comment]
Haha, sorry! We just recently started using Rollbar on our project, so the name has been on my mind. Thanks for the catch, fixed.

**Comment by AndrewSouthpaw** [comment]
Ping. :)

**Comment by CrossEye** [comment]
No, sorry, this looks good.

**Pull request merged**
