### PR TITLE
Adding promise aware tap function

### PR DESCRIPTION
**Pull request by bijoythomas**

### CODE REVIEW

**Comment by CrossEye** [comment]
Note:

```shell
> eslint ...
/home/travis/build/ramda/ramda/src/tapP.js
  24:19  error  Unexpected space before function parentheses            space-before-function-paren
  27:3   error  Expected indentation of 4 space characters but found 2  indent
  28:2   error  Newline required at end of file but not found           eol-last
```

But see https://github.com/ramda/ramda/issues/2074#issuecomment-277152148 before bothering to fix it.

**Comment by bijoythomas** [comment]
Thanks for the review @CrossEye 

I'm sort of lost between Promises and Ramda.

I published the request for the 'Q' library here:  https://github.com/kriskowal/q/pull/773
but got the response that it doesn't belong there.

I like ramda's composeP/pipeP, but without a tapP (promise aware), can't debug much and I guess vanilla ramda maybe does not want to work with promises anymore?

So, is this something that belongs in ramda fantasy given that promises are like tasks?

**Comment by bijoythomas** [comment]
tap works fine with composeP and pipeP as pointed out here: [https://github.com/ramda/ramda/issues/2074](url)

**Comment by CrossEye** [comment]
That's the reason people have been down on Promises: they're similar to Tasks/Futures, but not lawful.  One can't reason about them or use them in ways consistent with other types.

But I'm glad the current `tap` already works for you.  That makes things much easier.

**Pull request closed without merging**
