### PR TITLE
remove functions deprecated in v0.22.0

### PR DESCRIPTION
**Pull request by davidchambers**
`R.wrap` was deprecated in #1818 after discussion in #1387.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by buzzdecafe** [comment]
!
what hapened to my cow emoji?

**Comment by CrossEye** [comment]
Every time I go reaching for this @davidchambers, I'm coming to you to ask, "Now how do I do *this* one without `wrap`"  :smile:

@buzzdecafe:
Why, has you cow emoji been mooved?

**Comment by buzzdecafe** [comment]
> has you[r] cow emoji been mooved?

it's been changed into some cartoon-y thing; not the rugged, gritty, real-world cow i loved. going forward with 🐫

**Comment by davidchambers** [comment]
Are you referring to the cow's appearance in Gmail by chance, @buzzdecafe? GitHub recently switched from using images to using actual emoji in email messages, and Gmail uses a cartoonish emoji set. `:cow2:` still looks good on GitHub!

Also, @benperez may have a thing or two to say about your use of camels. ;)

**Comment by buzzdecafe** [comment]
hmmm, today it is back to the _cow noir_ i prefer. Maybe O:dromedary_camel: ?

**Pull request merged**
