### PR TITLE
update deprecation notices for *Indexed functions

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
Thank you.  I've been busy with houseguests.  Life should return to normal after tomorrow.

**Comment by Chris911** [comment]
What should we use instead of the *indexed functions? Let's say for a simple `forEach` with idx?

**Comment by davidchambers** [comment]
Have you tried [`R.addIndex`][1]?

```javascript
var forEachIndexed = R.addIndex(R.forEach);

forEachIndexed(R.bind(console.log, console), ['a', 'b', 'c']);
// -> a 0 ["a", "b", "c"]
// -> b 1 ["a", "b", "c"]
// -> c 2 ["a", "b", "c"]
```


[1]: http://ramdajs.com/docs/#addIndex

**Comment by Chris911** [comment]
Exactly what I need. Thanks.

**Pull request merged**
