### PR TITLE
Add boundProp function

### PR DESCRIPTION
**Pull request by mearns**
Add `boundProp` function to return the specified property from an object, and bind it to that object.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
i am sorry to say i am a bit cold on this PR.  Use of `this` is not something I think we should encourage. I am just one voice; but I would need to hear a compelling reason to include such a function.

**Comment by mearns** [comment]
@buzzdecafe I can certainly appreciate your reservations, given that this is a functional library. I guess my argument would be that this is a functional library for a language that supports objects and binding. To that point, ramda already provides a `bind` function to do the "objectionable" part of the added `boundProp` function, this just makes it easier to apply in some circumstances.

I don't think this function really encourages the use of `this`, per se, but it permits you to use ramda and functional techniques to more easily deal with existing uses of `this`.

The use case I encountered that prompted this PR was fairly general _if_ you're using objects with methods. I had a collection of objects that all had a particular named method on them. I wanted to map the collection of objects to a collection of the results of calling that method on each object. In plain old JS, it would simply be:

```javascript
const results = myObjects.map((obj) => obj.myMethod());
```

With out the added function, I would use ramda as follows:

```javascript
const results = myObjects.map(R.converge(R.bind, [R.prop('myMethod'), R.identity]).map(R.call);
```

With the added `boundProp` function, this can be reduced to:

```javascript
const results = myObjects.map(R.boundProp('myMethod')).map(R.call);
```

**Comment by svozza** [comment]
I agree, `R.bind` should be deprecated. :wink: Seriously though, if one needs the functionality, it is possible to just use an arrow function as that binds `this` in the appropriate way.

**Comment by mearns** [comment]
@svozza (meh). You can use an arrow function. You can use arrow functions to replace all of ramda's functions. The point is to make it more easier and more functional, right?

I don't feel strongly about this feature if there isn't general support for it. But I think if it's discarded specifically because it promotes the idea of object binding, then `bind` should deprecated as suggested above, for the same reason.

**Comment by buzzdecafe** [comment]
it's an open question where the "boundaries" of ramda are. It occupies an idiosyncratic space; not as strict as sanctuary, but more opinionated than underscore. `R.bind` is not something I find myself using, and it certainly is a concession to the realities of JS. 

If we agree that `bind` is a bit ... gross, then arguing that since `bind` is included, therefore sugar for `bind` should also be included, is not persuasive to me.

Your examples are useful:

```js
// 1
const results = myObjects.map((obj) => obj.myMethod());

// 2
const results = R.map(R.call, R.map(R.converge(R.bind, [R.prop('myMethod'), R.identity]), myObjects));

// 3
const results = R.map(R.call, R.map(R.boundProp('myMethod'), myObjects));
```

To my mind, example `1` is by far the best of the bunch for clarity. If your goal is to make a composable function, then you could use `invoker` as well, another of ramda's red-headed stepchildren: 

```js
// 4
// f :: [Obj] -> [???]
const f = R.map(R.invoker(arityOfMethod, 'myMethod')); 
```

**Comment by buzzdecafe** [comment]
> I thought R.bind, R.invoker ("ramda's red-headed stepchildren") are provided to enable using JS class methods in the same functional manner as "free-standing" JS functions? ES 6 class and HTML5 Api methods need to be bound to a suitable this when invoked. Why would Ramda deny them syntactic sugar? To encourage OO-style programming with those APIs?

It depends on what the goals of the library are. This area is really @CrossEye 's domain I think. If I may be so bold as to play his spokesman for a moment, I think he sees the lib as a gateway to a different way of thinking, and wants to smooth over the bits that don't fit well (e.g. `this` etc.)  I think that's where the red-headed stepchildren came from: @CrossEye attempting to bridge the gap from native JavaScript to a more "functional" idiom, or as you put it, "to enable using JS class methods in the same functional manner as 'free-standing' JS functions." 

That's not a priority for me at all; but that's why I said I am just one voice. 

> Btw. I do not see so many differences between `R.boundProp` and `R.invoker`.

I noticed the same thing; I agree.

**Comment by mearns** [comment]
Yup, `invoker` is very similar. I did a scan for functions that already solved my problem and did not find this one =\. The only thing I'll say about it is that with the proposed `boundProp`, you don't need to know the arity of the method, and specifically, you can invoke the resulting function with variable number of arguments.

**Comment by CrossEye** [comment]
I've been out of the loop for a while now.

@buzzdecafe has it right.  I originally imagined including pure versions of all the native methods, for things like `Date`, `Regexp`, `Array`, etc.  But early on we realized that his was unwieldy.  `Invoker` was a way to allow the users to do this for whatever objects they like.

But it is absolutely a concession to the way JS was and is being written rather than a principled addition to the library.  I can easily imagine a later version of Ramda removing these.  I never use `bind` myself, although I do use `invoker`.

`invoker` went through some serious changes in its early days (see #489 for some details).  We did consider variants where one didn't have to supply the arity, and ones with better handling of variadic functions.  The current version simply seemed to strike the best balance.  So I don't see much call for `boundProp`.

-----

@buzzdecafe: In the era of Trump and Spicer, "spokesman" takes on some pretty awful connotations!  :smile:

**Comment by buzzdecafe** [comment]
> @buzzdecafe: In the era of Trump and Spicer, "spokesman" takes on some pretty awful connotations! 😄

FWIW I think you come out slightly worse in that comparison

**Comment by mearns** [comment]
Based on this discussion, I'm comfortable closing this PR. If there is any different decision, feel free to re-open it =)

**Pull request closed without merging**
