### PR TITLE
Fix _Set regression in functions handling

### LINKED ISSUE #1987: 0.22 regression: R.uniq is broken for function (reference-eqaulity case)
```js
uniq([identity, identity, identity, identity, identity, identity]).length // 5
```

### PR DESCRIPTION
**Pull request by asaf-romano**
Closes #1987

### CODE REVIEW

**Comment by asaf-romano** [comment]
IMHO, this deserves a prompt hot fix, either as 0.23 if there is enough on master, or as 0.22.2.

**Comment by kedashoe** [comment]
There is quite a bit on master, :+1:  for v0.23.0

**Comment by CrossEye** [comment]
I unfortunately will not have much time this weekend.  But if I manage to find the time and no one has beat me to it, I will try to get 0.23.0 out.

**Comment by CrossEye** [comment]
I will also look over this fix more closely.  It looks simple enough, but I don't know the `_Set` code very well.

@scott-christopher: if you have a few minutes, would you be willing to check into this?

**Comment by scott-christopher** [comment]
Yep, apologies for the bug. This LGTM.

**Comment by CrossEye** [comment]
Thanks, Scott.  As expected, I did not find the time for a release over the weekend.  But I will try to do so soon.

**Pull request merged**
