### PR TITLE
Fix spelling of JavaScript

### PR DESCRIPTION
**Pull request by ligaz**
The correct spelling of JavaScript is to capitalize both **J** and **S** letters. More info [here]( https://www.quora.com/Should-the-s-in-JavaScript-be-capitalized).

### CODE REVIEW

**Comment by git-in-my-anus** [comment]
But Why?

**Comment by buzzdecafe** [comment]
uh-oh you've stumbled upon one of @CrossEye 's pet peeves. 
🏃

**Comment by ligaz** [comment]
I guess the reason is that I omitted the description. Fixed.

**Comment by CrossEye** [comment]
Not exactly a pet peeve.  But I use "Javascript" for a generic word to represent the family of languages adhering to the various versions of the ECMA-262 specification.  I reserve the trademarked "JavaScript" for the Mozilla implementation, and similarly, although rarely, use "JScript" for the MS version.

So if everyone feels strongly about changing this, feel free.  I will probably continue to write in the same manner, though.

**Comment by buzzdecafe** [comment]
LGTM :dromedary_camel:

**Comment by anton-rudeshko** [comment]
#393 :)

**Comment by CrossEye** [comment]
@anton-rudeshko:

Wow, I'd totally forgotten that we already did this!  :smile:

**Pull request merged**
