### PR TITLE
Code style consistencies

### PR DESCRIPTION
**Pull request by jimf**
The spirit of this pull request is to add additional code-style consistencies to help make project style preferences that aren't (currently) automated a little more self-discoverable.

Admittedly, I do feel a little silly opening this PR, but I do honestly think it will help somewhat with new contribution. Lemme know if any/all of these commits are unwanted and I can nix them.

### CODE REVIEW

**Comment by davidchambers** [comment]
I :heart: these changes!

**Comment by davidchambers** [comment]
@jimf, would you mind rebasing this branch? I'll merge this pull request once you have done so. :)

**Comment by jimf** [comment]
@davidchambers rebased/repushed.

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
Sorry, busy with other things.  This is great!  Thanks, @jimf!

**Pull request merged**
