### PR TITLE
Add links between docs for R.difference and related functions

### PR DESCRIPTION
**Pull request by pnavarrc**
Close ramda/ramda#1806 — Add links between the docs for `R.difference` and related methods.

Adds links between the documentation of the following methods:

- `R.difference`
- `R.differenceWith`
- `R.symmetricDifference`
- `R.symmetricDifferenceWith`

Related to https://github.com/ramda/ramda.github.io/issues/72, as the docs might need to be rebuilt.

### CODE REVIEW

**Comment by asaf-romano** [comment]
Please rebase to a single commit.

**Comment by buzzdecafe** [comment]
@asaf-romano you can squash & merge. See https://help.github.com/articles/about-pull-request-merge-squashing/

**Comment by pnavarrc** [comment]
I prefer to rebase myself if you don’t mind. I haven’t used `git rebase` before, but I want to learn to create nice pull requests on this project. :simple_smile:

**Comment by pnavarrc** [comment]
Done

**Comment by CrossEye** [comment]
Thank you!

**Pull request merged**
