### PR TITLE
Added possibility to use transducers with slice

### PR DESCRIPTION
**Pull request by Deadid**
Refers to #2264.
Added posibility to use transucers with slice. 
Test made from issue scenario.

### CODE REVIEW

**Comment by Bradcomp** [comment]
Hi @Deadid, thanks for the PR!  This looks pretty good, but can you fix the CI error you have? Also, can you add a note into the docs for `slice` along the lines of 
> Acts as a transducer if a transformer is given in list position.

**Comment by Deadid** [comment]
@Bradcomp  Done. Build was red because of lack of spaces :) Also I've added doc.

**Comment by kedashoe** [comment]
Does this support negative indexes like current `slice` does?

**Comment by buzzdecafe** [comment]
I wish we did not support negative indices.

**Comment by Deadid** [comment]
I assume no, but if it needed to merge this PR I could take a look at them later.

**Pull request closed without merging**
