### PR TITLE
remove array length caching

### LINKED ISSUE #1165: decide whether to cache array lengths
We currently mix these two styles:

```javascript
var idx = 0;
var len = xs.length;
while (idx < len) {
  ...
  idx += 1;
}
```

```javascript
var idx = 0;
while (idx < xs.length) {
  ...
  idx += 1;
}
```

Thanks to JIT compilation I imagine the performance is equivalent, in which case we should remove the manual length caching.

We should consistently apply our preferred style, whichever we decide that is.

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #1165

### CODE REVIEW

**Comment by CrossEye** [comment]
LGTM

I'd like to know that there's no substantial perf penallty for the multiple hits on `arguments.length`, used in `_checkForMethod` and `_dispatchable`.  But besides that, I'm :herb:

**Comment by davidchambers** [comment]
```console
~/github.com/ramda/ramda (remove-length-caching)
$ npm run-script bench

> ramda@0.14.0 bench /Users/dc/github.com/ramda/ramda
> scripts/benchRunner

┌────────────────────────┬──────────┬────────────────────────┐
│ concat                 │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _(s1).concat(s2)       │ 119731   │ 1733495.2993868925     │
├────────────────────────┼──────────┼────────────────────────┤
│ concat(s1, s2)         │ 526499   │ 9913683.07574263       │
├────────────────────────┼──────────┼────────────────────────┤
│ concat(s1)(s2)         │ 304527   │ 5761156.901117334      │
├────────────────────────┼──────────┼────────────────────────┤
│ concatS1(s2)           │ 570766   │ 11008473.932979671     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ curry                  │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _x4(100)               │ 749213   │ 13726160.815422656     │
├────────────────────────┼──────────┼────────────────────────┤
│ mult4(100)             │ 106264   │ 2020604.0085654685     │
├────────────────────────┼──────────┼────────────────────────┤
│ manual(100)            │ 5570728  │ 97039183.96935494      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ forEach                │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.each(nums, x2)       │ 192106   │ 3251370.2643140526     │
├────────────────────────┼──────────┼────────────────────────┤
│ forEach(x2, nums)      │ 212780   │ 3943708.1784927147     │
├────────────────────────┼──────────┼────────────────────────┤
│ forEach(x2)(nums)      │ 158623   │ 2896965.023277772      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ filter where           │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.filter(objs, {x: []… │ 13690    │ 243991.47146972714     │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(where({x: isEm… │ 31702    │ 536967.5970957589      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(where({x: isEm… │ 30985    │ 494771.935920338       │
├────────────────────────┼──────────┼────────────────────────┤
│ filterEmptyX(objs)     │ 34719    │ 579125.1348809317      │
├────────────────────────┼──────────┼────────────────────────┤
│ _.filter(objs, {y: fa… │ 53889    │ 658771.2016753219      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(whereEq({y: fa… │ 5144     │ 86459.42943717183      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(whereEq({y: fa… │ 5109     │ 87815.6518430276       │
├────────────────────────┼──────────┼────────────────────────┤
│ filterFalseY(objs)     │ 5192     │ 76519.83418021702      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ filter                 │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.filter(nums, isEven) │ 452902   │ 7532678.769573953      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(isEven, nums)   │ 281400   │ 4769320.454698883      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(isEven)(nums)   │ 172945   │ 2938641.460053222      │
├────────────────────────┼──────────┼────────────────────────┤
│ filterEven(nums)       │ 304567   │ 5117519.167135115      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ find where             │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.find(objs, {x: []})  │ 36761    │ 628593.7188061604      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(where({x: isEmpt… │ 75925    │ 1283628.1802717205     │
├────────────────────────┼──────────┼────────────────────────┤
│ find(where({x: isEmpt… │ 77086    │ 1365928.9044031862     │
├────────────────────────┼──────────┼────────────────────────┤
│ findEmptyX(objs)       │ 106428   │ 1913786.5864675932     │
├────────────────────────┼──────────┼────────────────────────┤
│ _.find(objs, {y: fals… │ 79226    │ 1289202.5471628718     │
├────────────────────────┼──────────┼────────────────────────┤
│ find(whereEq({y: fals… │ 15751    │ 256450.8074814438      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(whereEq({y: fals… │ 15664    │ 261802.64948034214     │
├────────────────────────┼──────────┼────────────────────────┤
│ findFalseY(objs)       │ 16058    │ 283228.61791303515     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ find                   │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.find(nums, isZero)   │ 306049   │ 5403930.762726237      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(isZero, nums)     │ 378402   │ 6446174.881990178      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(isZero)(nums)     │ 227885   │ 3888232.533549833      │
├────────────────────────┼──────────┼────────────────────────┤
│ findZero(nums)         │ 420541   │ 7674972.6809603        │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ findIndex where        │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.findIndex(objs, {x:… │ 55729    │ 943719.3056973628      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(where({x: i… │ 77624    │ 1301413.98748533       │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(where({x: i… │ 72897    │ 1239341.7408243103     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndexEmptyX(objs)  │ 99300    │ 1775058.6710537965     │
├────────────────────────┼──────────┼────────────────────────┤
│ _.findIndex(objs, {y:… │ 80169    │ 1348331.6613685961     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(whereEq({y:… │ 15397    │ 219433.42495671017     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(whereEq({y:… │ 15369    │ 265354.0275196965      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndexFalseY(objs)  │ 16520    │ 282756.13039595407     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ findIndex              │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.findIndex(nums, isZ… │ 315008   │ 5460109.855713883      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(isZero, num… │ 392647   │ 7153209.878807984      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(isZero)(num… │ 278301   │ 4335154.389627926      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndexZero(nums)    │ 427202   │ 7680495.153353835      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ indexOf                │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.indexOf              │ 2258000  │ 41311960.30529239      │
├────────────────────────┼──────────┼────────────────────────┤
│ indexOf(sq, nums)      │ 589060   │ 10509759.152793638     │
├────────────────────────┼──────────┼────────────────────────┤
│ indexOf(sq)(nums)      │ 354509   │ 6045836.069556295      │
├────────────────────────┼──────────┼────────────────────────┤
│ idxOf23(nums)          │ 703542   │ 11036409.513370384     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ isSet                  │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(unsortedBag)     │ 340781   │ 5784577.508862174      │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(unsortedSet)     │ 55232    │ 914921.6616760643      │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(sortedBag)       │ 340284   │ 5482935.984833239      │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(sortedSet)       │ 54807    │ 913115.9732889985      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ map                    │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.map                  │ 546857   │ 10292470.51768429      │
├────────────────────────┼──────────┼────────────────────────┤
│ map(sq, nums)          │ 253277   │ 4628456.067031392      │
├────────────────────────┼──────────┼────────────────────────┤
│ map(sq)(nums)          │ 166948   │ 3032384.0072071147     │
├────────────────────────┼──────────┼────────────────────────┤
│ mapSq(nums)            │ 268492   │ 4961153.793556652      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ maxBy                  │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.max                  │ 6119     │ 109468.31467813032     │
├────────────────────────┼──────────┼────────────────────────┤
│ maxBy(computer, nums)  │ 12338    │ 221593.06648292814     │
├────────────────────────┼──────────┼────────────────────────┤
│ maxBy(computer)(vals)  │ 12043    │ 208501.3973921895      │
├────────────────────────┼──────────┼────────────────────────┤
│ maxVal(vals)           │ 12217    │ 208254.42024855476     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ reduce                 │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.reduce(nums, add, 0) │ 862964   │ 15748069.965209203     │
├────────────────────────┼──────────┼────────────────────────┤
│ reduce(add, 0, nums)   │ 440966   │ 7662347.921540482      │
├────────────────────────┼──────────┼────────────────────────┤
│ reduce(add, 0)(nums)   │ 290971   │ 5239566.349593643      │
├────────────────────────┼──────────┼────────────────────────┤
│ reduceAdd(nums)        │ 665220   │ 12392563.979423178     │
└────────────────────────┴──────────┴────────────────────────┘

~/github.com/ramda/ramda (remove-length-caching)
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'upstream/master'.

~/github.com/ramda/ramda (master)
$ npm run-script bench

> ramda@0.14.0 bench /Users/dc/github.com/ramda/ramda
> scripts/benchRunner

┌────────────────────────┬──────────┬────────────────────────┐
│ concat                 │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _(s1).concat(s2)       │ 124146   │ 2195003.0730490177     │
├────────────────────────┼──────────┼────────────────────────┤
│ concat(s1, s2)         │ 506140   │ 7920259.439617167      │
├────────────────────────┼──────────┼────────────────────────┤
│ concat(s1)(s2)         │ 303766   │ 4834858.472460469      │
├────────────────────────┼──────────┼────────────────────────┤
│ concatS1(s2)           │ 564403   │ 9524922.153461764      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ curry                  │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _x4(100)               │ 734929   │ 13459331.964016944     │
├────────────────────────┼──────────┼────────────────────────┤
│ mult4(100)             │ 109841   │ 2020927.216280366      │
├────────────────────────┼──────────┼────────────────────────┤
│ manual(100)            │ 5341049  │ 97761967.27720293      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ forEach                │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.each(nums, x2)       │ 166917   │ 3047728.0902683297     │
├────────────────────────┼──────────┼────────────────────────┤
│ forEach(x2, nums)      │ 205808   │ 3581840.880353299      │
├────────────────────────┼──────────┼────────────────────────┤
│ forEach(x2)(nums)      │ 154048   │ 2121133.209007476      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ filter where           │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.filter(objs, {x: []… │ 13544    │ 214174.1991170311      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(where({x: isEm… │ 31896    │ 522410.595930874       │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(where({x: isEm… │ 31377    │ 506348.3396734291      │
├────────────────────────┼──────────┼────────────────────────┤
│ filterEmptyX(objs)     │ 35416    │ 610505.655880362       │
├────────────────────────┼──────────┼────────────────────────┤
│ _.filter(objs, {y: fa… │ 55163    │ 949836.5989461958      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(whereEq({y: fa… │ 4839     │ 67594.45837435969      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(whereEq({y: fa… │ 4766     │ 77448.4325921829       │
├────────────────────────┼──────────┼────────────────────────┤
│ filterFalseY(objs)     │ 4871     │ 90873.69081877891      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ filter                 │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.filter(nums, isEven) │ 448709   │ 7185297.067848325      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(isEven, nums)   │ 279481   │ 4799547.233550477      │
├────────────────────────┼──────────┼────────────────────────┤
│ filter(isEven)(nums)   │ 174067   │ 2972415.9082300463     │
├────────────────────────┼──────────┼────────────────────────┤
│ filterEven(nums)       │ 311884   │ 5583277.666495972      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ find where             │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.find(objs, {x: []})  │ 57438    │ 1055042.3891561215     │
├────────────────────────┼──────────┼────────────────────────┤
│ find(where({x: isEmpt… │ 78576    │ 1110602.1064529358     │
├────────────────────────┼──────────┼────────────────────────┤
│ find(where({x: isEmpt… │ 74761    │ 1032720.2470835843     │
├────────────────────────┼──────────┼────────────────────────┤
│ findEmptyX(objs)       │ 105315   │ 1895081.9178444692     │
├────────────────────────┼──────────┼────────────────────────┤
│ _.find(objs, {y: fals… │ 79148    │ 1342131.1595204046     │
├────────────────────────┼──────────┼────────────────────────┤
│ find(whereEq({y: fals… │ 14558    │ 247086.5971170506      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(whereEq({y: fals… │ 13977    │ 219602.7259737747      │
├────────────────────────┼──────────┼────────────────────────┤
│ findFalseY(objs)       │ 15602    │ 237427.64174068713     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ find                   │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.find(nums, isZero)   │ 312738   │ 5306409.454830966      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(isZero, nums)     │ 377756   │ 6125853.806188611      │
├────────────────────────┼──────────┼────────────────────────┤
│ find(isZero)(nums)     │ 240912   │ 4257889.989055237      │
├────────────────────────┼──────────┼────────────────────────┤
│ findZero(nums)         │ 417581   │ 7449887.572438911      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ findIndex where        │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.findIndex(objs, {x:… │ 56901    │ 1005104.0331645256     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(where({x: i… │ 78473    │ 1316616.6954056404     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(where({x: i… │ 72953    │ 1307883.0135741946     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndexEmptyX(objs)  │ 100508   │ 1499611.97090452       │
├────────────────────────┼──────────┼────────────────────────┤
│ _.findIndex(objs, {y:… │ 79867    │ 983151.4457318096      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(whereEq({y:… │ 13375    │ 159242.6675153269      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(whereEq({y:… │ 12958    │ 141795.5150311044      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndexFalseY(objs)  │ 14936    │ 231051.69900014257     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ findIndex              │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.findIndex(nums, isZ… │ 311702   │ 5561929.757599158      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(isZero, num… │ 385053   │ 7057571.203636907      │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndex(isZero)(num… │ 236291   │ 3973485.0078236465     │
├────────────────────────┼──────────┼────────────────────────┤
│ findIndexZero(nums)    │ 404134   │ 6154493.919892224      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ indexOf                │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.indexOf              │ 2150172  │ 37345976.55325065      │
├────────────────────────┼──────────┼────────────────────────┤
│ indexOf(sq, nums)      │ 569539   │ 10458626.111107958     │
├────────────────────────┼──────────┼────────────────────────┤
│ indexOf(sq)(nums)      │ 335802   │ 5994218.43126113       │
├────────────────────────┼──────────┼────────────────────────┤
│ idxOf23(nums)          │ 670715   │ 12273911.878097286     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ isSet                  │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(unsortedBag)     │ 336715   │ 6042601.345754156      │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(unsortedSet)     │ 53623    │ 919135.4513477418      │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(sortedBag)       │ 328532   │ 6065383.198240591      │
├────────────────────────┼──────────┼────────────────────────┤
│ isSet(sortedSet)       │ 52266    │ 968201.6180388867      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ map                    │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.map                  │ 507249   │ 9434765.50339793       │
├────────────────────────┼──────────┼────────────────────────┤
│ map(sq, nums)          │ 219444   │ 4061740.134534034      │
├────────────────────────┼──────────┼────────────────────────┤
│ map(sq)(nums)          │ 168779   │ 2800847.555131535      │
├────────────────────────┼──────────┼────────────────────────┤
│ mapSq(nums)            │ 259194   │ 4570708.8213240765     │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ maxBy                  │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.max                  │ 5552     │ 100258.47618910011     │
├────────────────────────┼──────────┼────────────────────────┤
│ maxBy(computer, nums)  │ 11339    │ 173886.07705504456     │
├────────────────────────┼──────────┼────────────────────────┤
│ maxBy(computer)(vals)  │ 9438     │ 165240.46871701957     │
├────────────────────────┼──────────┼────────────────────────┤
│ maxVal(vals)           │ 10348    │ 167439.7873462948      │
└────────────────────────┴──────────┴────────────────────────┘
┌────────────────────────┬──────────┬────────────────────────┐
│ reduce                 │ Count    │ Hertz                  │
├────────────────────────┼──────────┼────────────────────────┤
│ _.reduce(nums, add, 0) │ 876601   │ 14655532.977183793     │
├────────────────────────┼──────────┼────────────────────────┤
│ reduce(add, 0, nums)   │ 449685   │ 7783621.467906003      │
├────────────────────────┼──────────┼────────────────────────┤
│ reduce(add, 0)(nums)   │ 240298   │ 3917064.2104691835     │
├────────────────────────┼──────────┼────────────────────────┤
│ reduceAdd(nums)        │ 625651   │ 11372718.583521014     │
└────────────────────────┴──────────┴────────────────────────┘
```

**Comment by CrossEye** [comment]
This all looks fine to me.

There is clearly some noise in those numbers.  The average count dropped, something like 2.7% between the two runs, but the lodash ones increased 1.8%.  These aren't changes that would keep me up nights.

:+1:

**Comment by megawac** [comment]
I think this is dangerous for any public API functions. I'd be for reverting this

**Comment by CrossEye** [comment]
Based on the discussion in #1165, should we revert this?

**Comment by buzzdecafe** [comment]
yes

**Comment by jdalton** [comment]
Just a reminder when looking at the benchmark suite that many of them are bogus for comparisons. See #1128.

**Pull request merged**
