### PR TITLE
Remove Ramda devDependency

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by Bradcomp** [comment]
I am :bowtie:  on this, but I'd like at least one other person to weigh in on using `latest`.

**Comment by kibertoad** [comment]
Comes from discussion here: https://github.com/ramda/ramda/pull/2832

**Comment by Bradcomp** [comment]
>  I'm pretty sure that we can just replace it with @-latest. 

Sounds good enough for me! However, I just did a quick repo search and I am not sure that dependency is being used at all. It's possible we could remove it entirely.

@CrossEye Do you know where we are using it?

**Comment by CrossEye** [comment]
I can't find it, nor do I remember where we were using it before.  Perhaps it had to do with the docs before they were separated.  I think it can be safely removed.

**Comment by Bradcomp** [comment]
@kibertoad Can you try removing the dependency completely and see if that effects anything?

**Comment by kibertoad** [comment]
@Bradcomp Done!

**Comment by CrossEye** [comment]
Thank you @kibertoad!

**Comment by kibertoad** [comment]
@CrossEye np! Btw, any timeline on next Ramda release?

**Pull request merged**
