### PR TITLE
make R.converge a binary function

### PR DESCRIPTION
**Pull request by davidchambers**
Variadic functions with one or more "special" positions should be avoided. `R.converge` is currently in this category: the first argument is special, but the structure of `R.converge(f, g, h)` provides no indication of this. `R.converge(f, [g, h])` indicates that `g` and `h` are more closely related than `f` and `g`.

### CODE REVIEW

**Comment by scott-christopher** [comment]
I guess it's worth asking, should `converge` be limited to only accept unary functions? If it is limited to unary functions, `converge` could accept the argument that is to be passed to the list of functions as a third argument, e.g.:
```
((b, c, ..., n) -> v) -> [(a -> b), (a -> c), ..., (a -> n)] -> a -> v
// or
converge(add, mul(2), sub(3), 5); // 12
```
I guess it could also support further arguments after a list of non-unary functions, if we're willing to reintroduce variadic args.

**Comment by davidchambers** [comment]
I :heart: this idea, @scott-christopher. The type signature is complex enough when we pretend the list must contain unary functions. I frequently use `R.converge` to create unary functions; for binary functions a lambda is likely to be more appropriate.

**Comment by buzzdecafe** [comment]
i'd rather see `converge` defined as ternary: `(f, g, h) -> f(g(x...), h(x...))`. that seems simplest to me. i wonder if there is much call for more than two functions passing to `f`.

**Comment by kwijibo** [comment]
is `r.useWith` in this boat too? (ie, a variadic function with one or more special position)

**Comment by buzzdecafe** [comment]
yes, `useWith` suffers from the same problem.

**Comment by davidchambers** [comment]
Closing in favour of #1237

**Pull request closed without merging**
