### PR TITLE
add @see: R.view and R.set

### PR DESCRIPTION
**Pull request by adispring**
`R.view` and `R.set` are Lens's getter and setter functions. Add @see to each other may bring some convenience for people to read.

### CODE REVIEW

**Comment by Bradcomp** [comment]
Thanks @adispring! I think it might be worthwhile to remove `R.prop` from the `@see` list too, as they don't really fit here. Thoughts?

**Comment by CrossEye** [comment]
Yes on the change, yes to @Bradcomp's extension, but there's one thing missing.  We should also include `over` among these.  `view`, `set`, and `over` form a useful trio.

**Comment by adispring** [comment]
@Bradcomp @CrossEye 
Ok, I have removed `R.prop` from their @see lists, and add two more apis:  `R.lens` and `R.lensPath`.

**Comment by CrossEye** [comment]
:herb:

Looks great to me!

**Pull request merged**
