### PR TITLE
Generalize _xgroupBy to _xreduceBy

### PR DESCRIPTION
**Pull request by asaf-romano**
reduceBy, indexBy, countBy can now act as transducers; Bonus: groupBy no longer clones each step of the way in transducer-mode

### CODE REVIEW

**Comment by buzzdecafe** [comment]
lgtm; had to remind myself of the difference between `_hasMethod` and `_checkForMethod`

:cow2:

**Comment by asaf-romano** [comment]
I don't see hasMethod anywhere FWIW.

**Comment by buzzdecafe** [comment]
`hasMethod` expired in https://github.com/ramda/ramda/pull/1400

**Comment by asaf-romano** [comment]
@CrossEye  @davidchambers

**Comment by CrossEye** [comment]
:herb:

**Pull request merged**
