### PR TITLE
lint: allow unused parameters

### PR DESCRIPTION
**Pull request by davidchambers**
See plaid/sanctuary#31

### CODE REVIEW

**Comment by buzzdecafe** [comment]
hmmm. since it's just for that one function, seems to me it would be neater to comment that one function.

**Comment by davidchambers** [comment]
It's a philosophical question. I believe I have the right to give each function I define a `length` of my choosing (without using `void` or `R.arity`). JSHint currently prevents me from doing something valid.

**Comment by CrossEye** [comment]
:herb:

JSHint always prevents us from doing valid things; that's its job.  If it weren't valid, the interpreter would catch it.  We'll take out unused parameters where we see them, and if a few sneak by, I don't think it's the end of the world.

**Comment by buzzdecafe** [comment]
this means it is up to us to detect when unused params/vars occur. it's nice to have the tool catch that, especially since it is not just the three of us contributing. Let's follow the principle of least privilege. Clearly, we all agree jshint is a PITA in `arity`. I argue it should be bypassed there, and left in force everywhere else.

**Comment by CrossEye** [comment]
I don't have strong feelings on this.  I hate cluttering my source code with comments meant for the tools, but sometimes its a necessary evil.

**Comment by davidchambers** [comment]
> this means it is up to us to detect when unused params/vars occur.

Not so. There are four possible values for JSHint's [`unused`][1] option: `true`, `false`, `"strict"`, and `"vars"`. The last of these options disallows unused variables but allows unused parameters. Does this change your stance, @buzzdecafe? I littered Sanctuary's source code with `// jshint ignore:line` comments because I was unwilling to give up unreferenced variable detection. Yesterday I discovered I can have my :cake: and eat it too. :)


[1]: http://jshint.com/docs/options/#unused

**Comment by buzzdecafe** [comment]
yes, i did see that. i agree that is much better. i still think in a lib like this that is so concerned with arity, it's nice to have the security blanket.

**Comment by CrossEye** [comment]
mu

**Comment by davidchambers** [comment]
What does "mu" mean, @CrossEye?

**Comment by buzzdecafe** [comment]
https://en.wikipedia.org/wiki/Mu_%28negative%29

**Pull request closed without merging**
