### PR TITLE
revert propEq and pathEq, make prop/path first arg again

### PR DESCRIPTION
**Pull request by kedashoe**
See https://github.com/ramda/ramda/issues/3369#issuecomment-1641098850

### CODE REVIEW

**Comment by kedashoe** [comment]
Anyone can give this a quick look?

**Comment by kedashoe** [comment]
@Harris-Miller what are your thoughts on this? Shall we revert?

**Comment by Harris-Miller** [comment]
@kedashoe I'm voting **NO**. See here: https://github.com/ramda/ramda/pull/2938#issuecomment-1676049854

**Comment by kedashoe** [comment]
Closing, for previous argument order we can add `eqProp` in the future

**Pull request closed without merging**
