### PR TITLE
search script added

### PR DESCRIPTION
**Pull request by Rafi993**
search script has been added that will search all .js files for finding list of ramda functions used and make them into custom build using partial build script.
**example**
`node search -f C:\Users\human\Desktop\projectDir > custombuild.js`

### CODE REVIEW

**Comment by MattMS** [comment]
This is a nice idea, but will it actually work the way you have specified?
Wouldn't the `search` file need to be in the folder you are running `node search` from?

If this is to be continued, I would suggest using the [commander][1] package for command-line parsing, as it is used in [other scripts][2].

[1]: https://www.npmjs.com/package/commander
[2]: https://github.com/ramda/ramda/blob/master/scripts/build#L257

**Comment by Rafi993** [comment]
Yes you need to be in the scripts folder. when absolute path of the project folder is given to it as argument it does work.

**Comment by MattMS** [comment]
You may want to change this to a [npm bin script][1] by adding it to `package.json`.

I would also suggest renaming the script to something like `ramda-usage`.

[1]: https://docs.npmjs.com/files/package.json#bin

Having said all that, I'm wondering if this would be better suited as a separate package, given that it is a fairly specific use case.

**Comment by Rafi993** [comment]
@MattMS may be you are right. May be the partial builds ,search and similarl things should be moved to a separate repo as a CLI tool similar to lodash cli

**Comment by Rafi993** [comment]
That will keep the main repo clean and these additional tools independent of main repo.

**Comment by Rafi993** [comment]
That said since complicated build scripts are not here. Till then a separate CLI tool will be an overkill.

**Comment by davidchambers** [comment]
I wonder whether we'd be better served by addressing #1968.

**Comment by Rafi993** [comment]
@davidchambers  rather than porting to just es6 wouldn't it be better if it was typescript

**Comment by MattMS** [comment]
I agree with @davidchambers on this, which is why I suggested it may be suited to a separate package.

**Comment by Rafi993** [comment]
Closing this since it is not relevant anymore.

**Pull request closed without merging**
