### PR TITLE
Add examples of negative indexes to R.update and R.adjust

### PR DESCRIPTION
**Pull request by codeclown**
It was not clear that this functionality was supported until I looked at the tests.

### CODE REVIEW

**Comment by CrossEye** [comment]
I agree that this is worth doing, but while we're in here, I think that there are too many numbers in the examples.  It's harder to tell what the important index parameter means.

Would anyone object to something like this instead?:

```js
R.adjust(R.toUpper, 1, ['a', 'b', 'c', 'd']);      //=> ["a", "B", "c", "d"]
R.adjust(R.toUpper)(1)(['a', 'b', 'c', 'd']);      //=> ["a", "B", "c", "d"]
R.adjust(R.toUpper, -1, ['a', 'b', 'c', 'd']);     //=> ["a", "b", "c", "D"]
```

**Comment by codeclown** [comment]
I think that's a great idea. Any particular reason why you mixed single and double quotes?

I'll gladly update this PR after clarification on the quotes!

**Comment by CrossEye** [comment]
The double quotes were just pasted from the console.  I usually clean them up when I'm posting such a response, but I simply forgot this time.

**Comment by codeclown** [comment]
Updated to use characters/strings instead of numbers in examples.

**Comment by kedashoe** [comment]
> R.adjust(R.toUpper)(1)(['a', 'b', 'c', 'd']);
> R.update(1)('_')(['a', 'b', 'c']);

Do we need these examples? Just adds noise for me..

**Comment by codeclown** [comment]
I agree, they don't seem necessary nor consistent with other documentation (which generally lacks such currying examples). Shall remove while we're at it?

**Comment by buzzdecafe** [comment]
LGTM! :cow2:

**Pull request merged**
