### PR TITLE
Added example for take

### PR DESCRIPTION
**Pull request by bobiblazeski**
Added documentation example for take.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
this is great.

**Comment by buzzdecafe** [comment]
should i add an example for `take(theATrain)`?

**Comment by CrossEye** [comment]
Beautiful example!

**Comment by bobiblazeski** [comment]
:blush:

**Comment by CrossEye** [comment]
So long as no one define `var meOutTo = 9` and calls `take(meOutTo, theBallgame)` I think we're all safe.

**Pull request merged**
