### PR TITLE
Added a CHANGELOG.md file, mostly for recording breaking changes.

### PR DESCRIPTION
**Pull request by rue**
Proposal: though it’s a slight pain in a fast-moving project, it would be nice to see at least breaking changes at a glance.

This first draft includes changes from 0.9.1 to 0.10.0.

### CODE REVIEW

**Comment by davidchambers** [comment]
This is less comprehensive than the [upgrade guide][1]. Do you prefer this information to live in the repository itself?


[1]: https://github.com/ramda/ramda/issues/812

**Comment by rue** [comment]
Oh! As evidenced by my failure to find it, yes, I do think it would be nice to include a copy of the guide in the repo itself.

**Comment by CrossEye** [comment]
I think it should live in the repo, although I wouldn't mind vetting it in the format @davidchambers has been creating before adding new sections to a comprehensive changelog.

**Comment by rue** [comment]
That format (and content) in the guide is certainly superior—although links to docs might be good for new stuff. I don’t really have squabbles with the exact format, so long as breaking changes are clearly visible.

I can update this PR but it’s probably easier to close this, and just extract the raw markup from the guide and dump it into a file?

**Comment by davidchambers** [comment]
How about having __CHANGELOG.md__ link to the [upgrade guides][1]? The file would then act rather like a symlink. :)


[1]: https://github.com/ramda/ramda/issues?q=is%3Aissue+label%3Adocumentation+%22upgrade+guide%22

**Comment by buzzdecafe** [comment]
:+1: for pseudo symlink. (symsymlink?)

**Pull request closed without merging**
