### PR TITLE
rename R.createMapEntry

### PR DESCRIPTION
**Pull request by davidchambers**
Just an idea. `singleton` is quite a bit shorter than `createMapEntry`, though slightly less descriptive.

### CODE REVIEW

**Comment by scott-christopher** [comment]
I tend to associate `singleton` with lists more so than maps. Given the similarity to `R.of`, perhaps this could be called `R.mapOf`?

**Comment by davidchambers** [comment]
> I tend to associate `singleton` with lists more so than maps.

So do I.

> Given the similarity to `R.of`, perhaps this could be called `R.mapOf`?

I like it! :thumbsup:

**Comment by kedashoe** [comment]
I like the sound of `mapOf` better than `objOf`, but maybe `objOf` is more appropriate? Right now if you filter the ramda docs for `map`, `createMapEntry`/`mapOf` is the odd fn out, and if you filter for `obj` you get your object functions except you don't see `createMapEntry`/`mapOf`. Also `Map`s are here/on the way and `mapOf` would not give you one. Maybe even just `obj`? `var x = R.obj('a', 100);`

**Comment by scott-christopher** [comment]
Yeah, I agree that `objOf` would be more appropriate and consistent with Ramda naming than `mapOf`.

I actually have a helper function I use called `obj`, which is similar except it creates an object from multiple keys:
```js
var obj = R.unapply((keys) => R.compose(R.zipObj(keys), R.unapply(R.identity)));

var abc = obj('a', 'b', 'c');
abc(1, 2, 3); //=> {"a": 1, "b": 2, "c": 3}
```

**Comment by CrossEye** [comment]
I've never liked '`createMapEntry`'; it's never seemed to match.  '`objOf`' (or '`obj`') sounds _much_ better.

**Comment by buzzdecafe** [comment]
:+1: `objOf`

**Comment by CrossEye** [comment]
I think we have a winner.

**Comment by raine** [comment]
Woohoo!

**Comment by paldepind** [comment]
`objOf` is really nice.

Regarding the PR I think the old deprecated function should simply be an alias to the new name. In the current PR the source contains the same function twice.

**Comment by davidchambers** [comment]
I've renamed the function `objOf`, and made `createMapEntry` an :alien: as @paldepind suggested.

**Comment by buzzdecafe** [comment]
μ :cow2:

**Pull request merged**
