### PR TITLE
Update the README to reflect changes to Deno and Nest packages

### PR DESCRIPTION
**Pull request by sebastienfilion**
I've republished Ramda on Deno/x and Nest; this PR is to reflect the changes on the README.

### CODE REVIEW

**Review by Bradcomp — APPROVED** [review]

**Comment by sebastienfilion** [comment]
What can I do to get this merged in?

**Comment by CrossEye** [comment]
Probably just ping us again as a reminder!

Thanks.  Merged.

**Comment by sebastienfilion** [comment]
> Probably just ping us again as a reminder!
> 
> Thanks. Merged.

😅 thank you

**Comment by sebastienfilion** [comment]
> Probably just ping us again as a reminder!
> 
> Thanks. Merged.

By the way, I brain is mush lately; there wasn't a tone to my question, I was sincerely asking if there's something more I can do.
At any rate, I wish you all an Happy New Year - Thank you for everything you guys do.

**Comment by CrossEye** [comment]
> there wasn't a tone to my question

Nothing to worry about.  We are fairly slow to move around here.  The founders of this library set out to create a little educational repo for ourselves.  When it took off to become a popular library, we were never ready for it.  We still don't really know how to keep up with it.  So things are always falling through cracks.  Reminders are very good!

**Pull request merged**
