### PR TITLE
refactor example of liftN

### PR DESCRIPTION
**Pull request by safareli**
- in order to use arguments as expected we need to use normal function: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_arguments
- use R.sum for simplicity

### CODE REVIEW

**Comment by safareli** [comment]
anything on this?

**Comment by iofjuupasli** [comment]
Why not rest?

```js
(...args) => R.sum(args)
```

**Comment by safareli** [comment]
@iofjuupasli +1 actualy yap why not, did not thought about that at first

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
Somehow I missed this when it came through.  Thanks!

**Comment by safareli** [comment]
Welcome :3

**Pull request merged**
