### PR TITLE
Simplified `reduced` example

### PR DESCRIPTION
**Pull request by jethrolarson**

### CODE REVIEW

**Comment by kedashoe** [comment]
`it` adds some noise for me.. just a convention I'm not aware of? Is `it` short for "item" or is it the pronoun? Maybe just use `x`?

I'm a fan of simple examples though, :+1:

**Comment by CrossEye** [comment]
Same here.  `item` would be helpful.  Otherwise, :+1:

**Comment by fix-fix** [comment]
@CrossEye the example now contains typo inside condition:
`(acc, item) => it > 3 ? R.reduced(acc) : acc.concat(item)`

It refers to **`it`** variable, which is not defined, instead of `item` argument.

**Comment by jethrolarson** [comment]
Oops.

**Pull request merged**
