### PR TITLE
Revert "deprecate converge"

### PR DESCRIPTION
**Pull request by benperez**
Reverts ramda/ramda#1649

See discussion [here](https://github.com/ramda/ramda/issues/1447)

### CODE REVIEW

**Comment by asaf-romano** [comment]
🌷

**Comment by buzzdecafe** [comment]
yep, might as well. I see @asaf-romano has chosen his "stamp of approval" :smile: 

:cow2:

**Comment by CrossEye** [comment]
:herb:, But is @asaf-romano cheating by not using an emoji?  Stay tuned for the thrilling answer in our next installment!

**Comment by asaf-romano** [comment]
I really do love tulips, and it was in OS X's emojis palette. Therefore it's an emoji!

**Pull request merged**
