### PR TITLE
Update: `curryN` utilize optimized _curry1, _curry2, _curry3

### PR DESCRIPTION
**Pull request by Harris-Miller**
We got em, might as well use em

### CODE REVIEW

**Comment by Harris-Miller** [comment]
I'm unclear as to why the unit tests are failing

**Comment by kedashoe** [comment]
We keep the `this` context and pass along extra arguments to functions users give to us. Those internal _curry2 and _curry3 functions do not, so this would be a pretty big breaking change.

**Comment by Harris-Miller** [comment]
Ah I see. I did not notice that in the the `_curry1` and `_curryN` implementations. I could update `_curry2` and `_curry` to use `fn.call(this, ...)` and retain that behavior. Should work. Will give it a shot later this week

**Comment by Harris-Miller** [comment]
Tried with `fn.call()`, that fixed it. But those optimized `_curry2` and `_curry3` handles specific arity where `_curry1` and `_curryN` work with additional args. Not worth trying to add that in. Closing

**Pull request closed without merging**
