### PR TITLE
remove functions deprecated in v0.19.0

### PR DESCRIPTION
**Pull request by davidchambers**

### CODE REVIEW

**Comment by buzzdecafe** [comment]
i still think these are better, more descriptive names than `sequence` and `traverse`. But what are you gonna do. :cow2:

**Comment by davidchambers** [comment]
I was happy with the old names, but it's nice to have `R.sequence` :articulated_lorry: to `sequence` and `R.traverse` :articulated_lorry: to `traverse`.

**Comment by buzzdecafe** [comment]
yep, i agree. we can just point people to the Haskell docs

**Comment by CrossEye** [comment]
Yes, I definitely preferred `commute`, but complying with standards is generally a good thing.

**Pull request merged**
