### PR TITLE
Add debounce function to Ramda

### PR DESCRIPTION
**Pull request by Jkaveri**
Create a debounced that delays a pass in function util wait milliseconds. It is a helpful util when we need to create an event handler which handles a big rate of executions.

See: https://css-tricks.com/debouncing-throttling-explained-examples/

### CODE REVIEW

**Comment by buzzdecafe** [comment]
while i can see the usefulness of this procedure, i don't think it is a good fit for ramda. `debounce` is completely about side-effects. It does not even return a value.

**Comment by Jkaveri** [comment]
Thank you @buzzdecafe. I agreed it doesn't fit with ramda, maybe. However, It should useful in my project. I submit this request because I just want to contribute to ramda because I love it :).

**Comment by Jkaveri** [comment]
If It looks like a useless to you guys :). we can close this request :).
Thank you for your comment :)

**Comment by davidchambers** [comment]
It's certainly not useless, @Jkaveri. Everything in its right place, as the Radiohead song goes. Ramda just isn't the right place for this function.

I appreciate your enthusiasm for Ramda. :)

**Comment by buzzdecafe** [comment]
there are some contrib libraries cropping for extending ramda in different directions (e.g. i think there are some on the [list of related projects](https://github.com/ramda/ramda/wiki); not a complete list!)

Thanks for the kind words

**Pull request closed without merging**
