### PR TITLE
Add unpkg and jsdelivr field to package.json

### PR DESCRIPTION
**Pull request by porsager**
It would be great to be able to use ramda directly through https://unpkg.com/ramda

### CODE REVIEW

**Comment by git-in-my-anus** [comment]
Maybe the more commonly used field `"browser"` should be added instead?

**Comment by porsager** [comment]
I did that at first, but I didn't want to be the one who broke peoples code if they had their bundler set up to use the browser field if available (I know rollup has an option to do that at least) 😊

But yes, generally it would be best with browser, but I somehow think that could be considered a breaking change. 
I can see the issue targeting unpkg directly, because then jsdelivr should probably be added as well.

**Comment by MartinKolarik** [comment]
To make it even more complicated, unpkg is going to remove support for `browser` 😄 The best option right now is setting both `jsdelivr` and `unpkg` which doesn't risk breaking anything and will work with both services.

**Comment by porsager** [comment]
Ah, thanks @MartinKolarik for that info.. Just read through the thread at https://github.com/unpkg/unpkg-website/issues/63

I'll add jsdelivr to this pull request as well, and cross my fingers a common solution like a `cdn` field will win over in the future.

**Comment by MartinKolarik** [comment]
>cross my fingers a common solution like a cdn field will win over in the future.

jsDelivr already supports `cdn` but Michael wasn't interested in adding support to unpkg so there isn't much we can do unless his users start asking for it.

**Comment by CrossEye** [comment]
I see no reason not to do this.  :herb:

Any objections?

**Comment by buzzdecafe** [comment]
:cow2:

**Pull request merged**
