### PR TITLE
restore aliases for reduce*

### PR DESCRIPTION
**Pull request by buzzdecafe**

### CODE REVIEW

**Comment by CrossEye** [comment]
Note that this function is not currently dynamically dispatched, so it's not an issue, but when we want to connect dynamic dispatch with aliases, we're going to have to use separate calls to `checkForMethod` for each alias, or find a different way to do the dispatch.

**Comment by buzzdecafe** [comment]
agreed. for now, i'd like to restore this and get 0.9.2 out

**Comment by buzzdecafe** [comment]
... although that should be a simple matter of changing the implementation to:

```javascript
// in foldl.js:
module.exports = _curry3(_checkForMethod('foldl', _foldl));

// in reduce.js:
module.exports = _curry3(_checkForMethod('reduce', _foldl));
```

**Comment by CrossEye** [comment]
Right, although that means we no longer have simple aliases.

    R.foldl === R.reduce; //=> false

**Comment by buzzdecafe** [comment]
fair enough--i'm not sure if that is bad or not. would you expect `foldl` to dispatch to an object with a `reduce` method? seems a little weird

**Comment by buzzdecafe** [comment]
*ping*

**Comment by davidchambers** [comment]
I have no objections.

**Comment by jschomay** [comment]
Thank you!

**Pull request merged**
