### PR TITLE
R.append and R.prepend work for strings

### PR DESCRIPTION
**Pull request by GingerPlusPlus**
I haven't changed `@param` and `@returns` in JSDoc.

#2418.

### CODE REVIEW

**Comment by CrossEye** [comment]
I'd like to see what other members of the @ramda/core team think of this first.  Does this stray too far from our philosophy?  In other words, `concat` works on both Strings and lists (as well as other Semigroups) because we delegate it.

Is there a good reason to extend `prepend`/`append` to Strings?  Are there good reasons not to (besides the obvious API bloat, which might be enough on its own)?

**Comment by CrossEye** [comment]
((:bell:)) @ramda/core

**Comment by Bradcomp** [comment]
I have a somewhat odd middle viewpoint here. I wouldn't mind if `append` and `prepend` _worked_ with strings, but I wouldn't like it if it was documented.

Strings are kinda weird in Javascript because there's no such thing as a `char` type, and because they don't actually work like Arrays either. You can't nest them, for instance.

When I append or prepend something, given the signature, and what the words mean, I know what to expect. 
```
prepend (1, [2, 3, 4])  // => [1, 2, 3, 4] 

prepend ([1], [2, 3, 4]) // => [[1], 2, 3, 4]

prepend ([1, 2], [3, 4]) // => [[1, 2], 3, 4]
```

with that in mind, what should prepend ("ab", "cd") return? Well, the only sensible answers are either "abcd" or ["ab", "cd"], neither of which really really capture the signature of append. The first takes String to be both the unit and the container, while the second assumes you just forgot the Array.

This is, to me, because while String is a Monoid, it isn't a List (while JS Arrays are both a Monoid and a List). `concat` is the function we use to join two monoids, and semantically I think it makes more sense to use that then it does to use these two list-specific functions.

That being said, I think that treating the functions as `concat` and `flip(concat)` for Strings would be a sane default to have, but I certainly wouldn't want to encourage that use.

**Comment by CrossEye** [comment]
@Bradcomp: I'm usually fine with having undocumented, but somewhat useful behavior.  But for me, that is because we don't do much type-checking, and I'm perfectly willing to take whatever behavior falls out of our implementation for those cases we don't explicitly support.

Intentionally adding behavior without documenting is uncomfortable to me.

**Comment by CrossEye** [comment]
@Bradcomp: I agree, but would still love to hear from more of the @ramda/core team.

**Comment by paldepind** [comment]
I don't think this is necessary. `R.prepend("a", "bcd")` is equivalent to `R.concat("a", "bcd")` and `R.append("d", "abc")` is just `R.flip(R.concat)("d", "abc")`.

If JavaScript had had a character type I think supporting that in `R.prepend` and `R.append` would have been nice. But since it doesn't I think using `R.concat` is more appropriate.

**Comment by CrossEye** [comment]
@paldepind: I agree.  I've been on the fence about this one.  But there is no common abstraction between lists and strings that we're trying to support for all our list functions.  Since this is easily achievable with other of our functions, I don't see the need.

**Comment by GingerPlusPlus** [comment]
I agree with you after all. Special casing it is not that good idea.

**Pull request closed without merging**
