### PR TITLE
Change const to var

### PR DESCRIPTION
**Pull request by screendriver**
Because `const` will break on older browsers like in iOS 9.3

### CODE REVIEW

**Comment by CrossEye** [comment]
:herb:

Thank  you.  I don't know how these snuck in.

**Comment by screendriver** [comment]
Thank you. That was quick. This should be released as soon as possible because without that fix some applications will break without knowing what's going on 😉 (I had this kind of issue for example)

**Comment by CrossEye** [comment]
I'll try to get to it tonight.  There's some other things that should make it into a quick release.

**Comment by screendriver** [comment]
Great! 🎉

**Pull request merged**
