### PR TITLE
fix ap signature

### PR DESCRIPTION
**Pull request by benperez**
This was brought up in https://github.com/ramda/ramda/issues/1776

### CODE REVIEW

**Comment by davidchambers** [comment]
Nice improvement, Ben. :)

Shall we also include the more general `Apply f => f (a -> b) -> f a -> f b`?

**Comment by benperez** [comment]
I seem to recall that at some point there was talk of supporting multiple signatures per function. Where did we land on that?

**Comment by davidchambers** [comment]
> Where did we land on that?

See [`R.concat`][1]. ;)


[1]: http://ramdajs.com/docs/#concat

**Comment by benperez** [comment]
⚡

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
:herb:

**Pull request merged**
