### PR TITLE
update chain docs to mention FL

### PR DESCRIPTION
**Pull request by benperez**
closes https://github.com/ramda/ramda/issues/1732

### CODE REVIEW

**Comment by buzzdecafe** [comment]
this is great, thanks. 

An aside: I don't like mentioning in the docs that a function dispatches; we should simply point out that it supports FL chains. That FL chains are OO-style methods and so we dispatch is an implementation detail that I don't think we should broadcast.

But that's a bigger issue than this PR; this looks fine to merge to me.

:cow2:

**Comment by benperez** [comment]
> I don't like mentioning in the docs that a function dispatches

Fair enough. It might make sense to remove mention of dispatching in a different PR.

**Comment by buzzdecafe** [comment]
> It might make sense to remove mention of dispatching in a different PR.

Yes, i don't see any reason to hold this up.

**Comment by davidchambers** [comment]
Shall we update the type signature while we're at it?

```haskell
chain :: Chain m => (a -> m b) -> m a -> m b
```

**Comment by benperez** [comment]
:zap:

**Comment by CrossEye** [comment]
I guess this is what I get for going offline for a few days, but I don't agree with that being the only type signature.  I'd like to take some of the lessons from #1578 to heart and make sure that the simplest cases don't get short shrift in our documentation.

I would have no problem at all with

```haskell
chain ::  (a -> [b]) -> [a] -> [b]
      :: Chain m => (a -> m b) -> m a -> m b
```

But let's not lose touch with our simple cases.

**Comment by benperez** [comment]
@CrossEye I also like the idea of keeping 2 signatures: one simple one for the default implementation and one generic for the people interested in FL compatibility. How do you suggest we do this using the existing system? One signature per line?

**Comment by CrossEye** [comment]
Yes, we can already handle this.  See [`take`][ta] for an example.

```js
 * @sig Number -> [a] -> [a]
 * @sig Number -> String -> String
```

screenshot-2016-04-16a

  [ta]: http://ramdajs.com/docs/#take

**Pull request merged**
