### PR TITLE
fix(3232): fix R.groupBy when used as transducer

### LINKED ISSUE #3232: groupBy (permanently?) enters a broken state when used as transducer
While `groupBy` is one of the Ramda functions documented as being usable as a transducer, and I believe this worked years ago when I last tried it, now it appears to pass through every item into every group list. After this, every subsequent use of `groupBy` (as a transducer or otherwise) will be cloned as the starting accumulator for each group.

I'm guessing there was an update to `reduceBy` at some point that broke the arity to cause this but haven't quite gone through all the layers of indirection to narrow it down.

## Repro

```javascript
const {groupBy, into, range} = require('ramda');

const evenOdd = x => x % 2  === 0 ? 'even' : 'odd';
// this works fine.. if done *first*
groupBy(evenOdd, range(1, 10); // got expected {"odd":[1,3,5,7,9],"even":[2,4,6,8]}

into({}, groupBy(evenOdd), range(1, 10));
// expected: {"odd":[1,3,5,7,9],"even":[2,4,6,8]}
// actual: {"odd":[1,2,3,4,5,6,7,8,9],"even":[1,2,3,4,5,6,7,8,9]}

// It appears to simply pass through all values for each key returned by the group function. After this, any 
// subsequent use by `groupBy`, even in the non-transducer form, appends the results to of the previous list:

groupBy(x => String(x.length), ['a', 'ab', 'abc']);
// expected {"1":["a"],"2":["ab"],"3":["abc"]
// actual: '{"1":[1,2,3,4,5,6,7,8,9,"a"],"2":[1,2,3,4,5,6,7,8,9,"ab"],"3":[1,2,3,4,5,6,7,8,9,"abc"]}'
```

## comparing `countBy`

```javascript
const evenOdd = x => x % 2 === 0 ? 'even' : 'odd';
R.into({}, R.countBy(evenOdd), R.range(1, 10)); // { odd: 5, even: 4 }
```

### PR DESCRIPTION
**Pull request by xgbuils**
It fixes #3232

### CODE REVIEW

**Comment by xgbuils** [comment]
Sorry, I didn't see [jaawerth](https://github.com/jaawerth) fix. I'm gonna close it.

**Comment by jaawerth** [comment]
While I did submit  quick-and-dirty fix, I think yours might actually be better - I think the problem is that transducers are inherently stateful (especially in the step function), they just happen to hide the state under the hood (this being a huge optimization in clojure, or in JS using `ImmutableJS`, since you can use transient mutable versions of your immutable structures to save the overhead while still looking stateless to the outside observer:


I don't know this codebase super well, but if I had to guess, I think your fix could end up solving similar issues if there are other "also usable as a transducer" reductions that aren't being tested in transducer form.
. 
The `step` function in particular is often some kind of state mutation, just bookended betwen the `init` and `result` functions, though in JS this is a bit made up as we go since clojure gets immutability for free and outright names the mutable versions of its structures "transients".

Other JS implementations of transduce, I usually see this handled by the final transform created by e.g. `into`, where `into([], ...)` "clones" the array when it's empty, but if a populated plain object/array is passed in, they just mutate, or leave it up to a `@@transducer/init` function to take care of things. I don't know what'd be best for ramda, just figured it'd be worth mentioning.

**Comment by xgbuils** [comment]
Ok, I'm gonna open the PR because my solution seems more consistent with the no-transducers implementation.

After reading what you say, @jaawerth, I don't like to much the _clone approach we have in functions like `into` and maybe delegating in `@@transducer/init` function is better. But I think it's something that I have to review more deeply. Having the same solution than the default implementation can reduce the number of unexpected behaviours now.

**Comment by customcommander** [comment]
I am having a busy week so worse case scenario I'm going to look at this over the weekend. But thank you both for coordinating your efforts. It's great to see 🙇‍♂️

**Comment by adispring** [comment]
Sorry for introduce the bug, I wll see what happen here,

**Comment by adispring** [comment]
I spend some time to see the source code of `groupBy`, `reduceBy` and `_xreduceBy` , find out that this fix is more robust.

When using `reduce` and `reduceBy`, People should not mutate the acc in place in general. But `groupBy` has break this rule for performance, and use one hack method to let itself behave normally, as follows:

```js
var groupBy = _curry2(_checkForMethod('groupBy', reduceBy(function(acc, item) {
  if (acc == null) {
    acc = [];
  }
  acc.push(item);
  return acc;
}, null)));
```

when `groupBy` act as a transducer, if `acc` is `null`, this means it's a new subgroup iteration, then `groupBy` make a new empty array `[]` to subgroup, then each subgroup has its own acc.

**Comment by adispring** [comment]
All other Ramda apis base on `reduceBy` (`countBy`, `indexBy`) don't have the same problem, because they do not mutate `acc` in place.

```js
var countBy = reduceBy(function(acc, elem) { return acc + 1; }, 0);

var indexBy = reduceBy(function(acc, elem) { return elem; }, null);
```

**Review by CrossEye — APPROVED** [review]
Thank you very much.  This looks great!

**Review by customcommander — APPROVED** [review]

**Pull request merged**
