### PR TITLE
Add allIndexed

### PR DESCRIPTION
**Pull request by jeduden**
Currently this commit increases code duplication:
- Unittests have been copied and modified from "all" since the unittests from "all" should also apply to allIndexed.

### CODE REVIEW

**Comment by CrossEye** [comment]
I'm not overly worried about duplication in the test suite; although obviously, even there, DRYer is better.

But I'd like to know more about use-cases for this.  The example in the inline docs doesn't convince me, and there's no real examples in the test cases.

What real problems does it solve?

We've resisted including similar functions before because we could see little need.  See a very long discussion in #452 for example.

I really need to get back to considering #484, which might make this easier to do.

Can you give a convincing argument for this function?

**Comment by jeduden** [comment]
Sure.
General arguments
1. This is a step towards providing indexed versions for all functions that iterate over an array like object. 
2. This makes the usage of the library easier in the sense that you dont need to rethink your algorithms if the one that you got uses the index.
3. if you look at the code of foreach and its siblings , index and list are available.
4. ecmascript versions provide these.
5. If you need the index and ramda does not provide it you might have to add code to recreate it.  Worst case developers add an index variable outside of the callback function and increase it each time. 

Use case based arguments
6. Any algorithm that can be implemented with forEach but that would benefit from the short circuit behavior of all.
7. Find index of unescaped quote. See example in testcase.
8. find index of first pair that where less is true. Used in sorting algos.

**Comment by buzzdecafe** [comment]
I don't see why point 1 should be a goal; point 2 is reasonable, although I have yet to see a use case for index with `all` apart from pairwise processessing. As to 3, I would love to *remove* `forEach` from the library! But it is almost inescapable if you want to work with the DOM. 4 is not a concern for us, I don't think we are trying to recreate native interfaces.

point 5 is a little persuasive, but I am not particularly moved by 6 and 7 which are better implemented with `findIndex`. As noted above, the only use case I've seen that may be simplified with an index to `all` is when processing elements of an array in a pairwise fashion, So far, that has not been an issue.

**Comment by CrossEye** [comment]
I'm not going to have much time before the weekend, but I will take another look then at #484.  I think that would solve this in a generic fashion and still reduce the API footprint.

**Comment by CrossEye** [comment]
Part of my problem is that this code feels very much outside the spirit of Ramda:

    var firstIndexOf5ThatIsNotFollowingA4;
    R.allIndexed(function(num, idx, list) {
      if( num === 5 && list[idx-1] != 4 ) {
        firstIndexOf5ThatIsNotFollowingA4 = idx;
        return false; // use short circuit to stop here.
      } else {
        return true;
      }
    },[4, 5, 1, 2, 5, 6, 5]);

Creating a side-effect inside a call to `allIndexed`, and making that an example of how one would want to use the library is definitely on the wrong track to me.

On the other hand, dealing with pairs of elements (or triples, etc.) from a list seems a very useful possibility, and I could easily see something like:

    R.pairwise(['a', 'b', 'c', 'd']); //=> [['a', 'b'], ['b', 'c'], ['c', 'd']]

which would probably be a gloss on `nWise` or some such:

    R.pairwise = R.nWise(2);

so that it could create tuples of length `n` as necessary.

This still wouldn't solve your whole issue as you need back the index, but together with `addIndex` from #484, I think you could write something simpler for a case like this.

**Comment by jeduden** [comment]
In general i like the idea of pairwise/nwise. And i agree that together
with addIdx it solves my current use cases.

Thinking about pairwise and also nwise, i realized that they are (likely
common) special cases of a  moving window function , that maps an index to
an array of indices, combined with a mapping function, that performs the
element lookup for each of the indices.

One aspect that i am looking a good solution for is the aspect of short
circuiting.
A function like findIndex would support these special cases.

More generally, reduce would also work but currently reduce doesnt offer
short circuiting. (Also es6 dont offer it ).

An extended version of reduce that behaves like the following might be
worth consideration:

Reduce( callback, initial )
Where callback is a function(agg, element, (index, list ), stop )
stop is a function that signals to reduce to stop iterating after the
callback.completes.
Alternative to the stop callback would be to return not simply the return
value but a pair. The result of reduce and a boolean that signals when to
stop.

**Comment by CrossEye** [comment]
`findIndex` is already a concession that doesn't thrill me.  In the abstract, the data type that Ramda works with is _lists_, and lists don't really have indices.  Features like maps, filters, and folds operate on more general data structures as well.  In fact, Javascript doesn't have a `List` type, so we use the closest equivalent, the (non-sparse) array.  But we do try to keep in mind that underneath we want to think about these structures as lists, and we would like one day to ensure our functions work on related data structures that may not have a notion of an index, something like streams, for instance, or trees.  I discuss this at greater length in https://github.com/ramda/ramda/issues/729#issuecomment-70351882.

`findIndex` doesn't well expand in this direction, and so I'm less than thrilled to have it.  I recognize that there are plenty of times its useful, and I'm not looking to get rid of it, but it strikes me as further from the core of Ramda than, say, `find`.

-----

I don't see a reason for `reduce` to have a stop-iteration.  The idea of `reduce` (`fold` in many functional languages) is to fold a data structure down to a value.  That you could stop early is not such a big deal in that circumstance.  Obviously there are other functions that do have a reason to stop iteration, ones like `find`, or short-circuiting ones like `any*` or `all*`.  But I would do those where needed, because in general, operating on a data structure should be thought of as in some way operating on a whole.

**Comment by jeduden** [comment]
> But I would do those where needed, because in general, operating on a
data structure should be thought of as in some way operating on a whole.
It is fine to declare ramda as a library that supports functional
programming for algorithms and data structures that focus on lists/sets
only and that short circuiting and random access data structures and
algorithms are not a focus for Ramda.

While I personally believe that random access and short circuiting have a
place in a pure functional library, it can be very well that Ramda is not
that specific library
If that is the case, it would be helpful for managing expectations about
the library's focus if you could make this more explicit in the mission
statement.

**Comment by buzzdecafe** [comment]
sure, clojure shourt-circuits reduce when it sees

**Comment by jeduden** [comment]
Clojures way to mark values as reduced is clearly an additional alternative provide short circuit functionality to the application.
One thing I am not clear on, if this kind of extension to Ramda's reduce is aligned with the goals of the library and that if I send a pull request that implements one of these approaches has a chance of being accepted.

**Comment by CrossEye** [comment]
I recently published an article on my ideas about the [philosophy of Ramda][pr]; one of the points I stress is that we want to keep Ramda's API shallow and simple.  Functions in Ramda don't do a lot of "well if the parameter is a String, do this, an object do that, or a function do the other."  We don't offer optional parameters anywhere.

I can't imagine a way to update `reduce` with a stop-iteration that didn't run afoul those notions of simplicity.  That doesn't mean there couldn't be another distinct folding function that did have it, if you're interested in presenting one.  Since I haven't personally found much need for one, I might take some convincing to see the benefits.  It would have to demonstrate some usefulness that can't be simply achieved through the current short-circuiting functions.

But @buzzdecafe or @davidchambers might have different feedback.


  [pr]: http://fr.umio.us/the-philosophy-of-ramda/

**Comment by kedashoe** [comment]
Short circuiting `reduce` is necessary for transducers, so if you guys go that way users will ipso facto gain this flexibility.

**Comment by jeduden** [comment]
Yeah. I looked into transducers more indepth yesterday. They seem to
address a lot of my issues.

Transducer-js uses closures approach to shortcicuiting (i.e. wrapping the
return value ). Is that an approach that resonates with the people here ?

**Comment by CrossEye** [comment]
@kedashoe: Does this imply that users of `reduce` will have to change their code?

**Comment by jeduden** [comment]
@CrossEye : No. If wrapping is used, the change is transparent to any implementation that care about short circuiting. 
Both transducers-js and transducer.js use actually the same technique.
see : https://github.com/cognitect-labs/transducers-js/blob/master/src/com/cognitect/transducers.js#L130

**Comment by kedashoe** [comment]
@CrossEye users should be fine, the PR passes the current reduce test suite, I also have a test or two for `reduce` in test/transduce.js. The reducing loop simply checks if the user's function returns `reduced`, eg

https://github.com/kedashoe/ramda/blob/f28db55ed88b541ae3c466f14167c1a8816daf6d/src/internal/_reduce.js#L22

This reminds me, I didn't mention in the PR thread but reduce itself will also be able to handle all data types (objects, Immutable classes, streams, etc)

**Comment by jeduden** [comment]
Looking at https://github.com/ramda/ramda/pull/865 it looks like that it would help my use cases quiet a bit: since provides short circuiting and transducers which themselves somewhat help in my use cases.

**Comment by buzzdecafe** [comment]
see also #878

**Comment by davidchambers** [comment]
If someone can demonstrate how #878 addresses this need we can close this pull request.

**Pull request closed without merging**
