### PR TITLE
add R.composeK and R.pipeK

### LINKED ISSUE #1197: function equivalent of "do" notation
This idea is being discussed in plaid/sanctuary#53. I won't duplicate the proposal, but I will open a Ramda pull request if we decide Ramda should provide this function.

@buzzdecafe is eager to *reduce* the number of composition functions, so may not want to add this one, though @joneshf has intimated that this behaviour could be provided by a more general `R.compose`.

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #1197

### CODE REVIEW

**Comment by buzzdecafe** [comment]
LGTM. :cow2:

not sure what the deal is with the build. "npm license has expired"??? wtf?

**Comment by CrossEye** [comment]
Wow, I thought @buzzdecafe might have apoplexy about yet another `compose` function.  And yet he's the first to sign off?  I have no direct objections.  I understand the desire.  But I agree with the goal @buzzdecafe has been discussing of reducing these things.  So it's only a tentative :+1:

**Comment by buzzdecafe** [comment]
well, @davidchambers removed `composeL` so he is playing with house money. Also, I think we can probably unify `compose` and `composeP`. I'll do a PR for that. And then we can look at folding `K` in there as well, so we have one `compose` to rule them all.

**Comment by buzzdecafe** [comment]
... now if this was derived from `slice` and there was a test exposing the implementation, then it might be a different story.

**Comment by davidchambers** [comment]
> And then we can look at folding `K` in there as well, so we have one `compose` to rule them all.

It doesn't make sense to me to combine two fundamentally different composition functions. Having one function handle all these compositions (if it's even possible) is too much magic for my liking:

  - `b -> c` ∘ `a -> b`
  - `b -> c` ∘ `a -> m b`
  - `b -> m c` ∘ `a -> b`
  - `b -> m c` ∘ `a -> m b`

**Pull request merged**
