### PR TITLE
Revert "`adjust` and `assoc` now returns the same instance if the val…

### PR DESCRIPTION
**Pull request by buzzdecafe**
Reverts ramda/ramda#998

see discussion in https://github.com/ramda/ramda/issues/1025

### CODE REVIEW

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
:herb:

**Comment by etherealite** [comment]
Ramda V0.21.0 adjust has a confusing behavior where its return type is incongruent with its input. When given an empty string, it returns a string, but when given a non-empty string, it returns an array of single character strings.

```
R.adjust(R.identity,0, "")  //=> ""
R.adjust(R.identity,0, "abc")  //=> ["a", "b", "c"]
```

To me, this behavior feels like a confusing 'gotcha'. I would expect the type of the return to be an array in both of the above cases.

**Comment by buzzdecafe** [comment]
@etherealite i agree that is bad behavior. Do you think it would be better to simply return `[ ]` or throw since String is an invalid input type? Or some other behavior?

I'm leaning more and more in the direction of :boom: rather than try to paoper over it.

**Comment by etherealite** [comment]
Plus one for the Michael Bay option.

**Pull request merged**
