### PR TITLE
Define indexBy and countBy in terms of reduceBy

### PR DESCRIPTION
**Pull request by asaf-romano**

### CODE REVIEW

**Comment by davidchambers** [comment]
:deciduous_tree: Very nice!

**Comment by buzzdecafe** [comment]
indeed, should also transduce, so that is nice too

**Comment by asaf-romano** [comment]
@buzzdecafe hrm? there's no _xreduceBy (there probably could be, and at that point we would remove _xgroupBy).

**Comment by buzzdecafe** [comment]
sorry my mistake; since it is defined in terms of `reduce` i jumped to the conclusion. but of course we are specifying the output container, so it won't transduce as is.

**Pull request merged**
