### PR TITLE
fix lint error

### PR DESCRIPTION
**Pull request by davidchambers**
It would be nice if GitHub indicated in a pull request whether the tests will pass if the pull request is merged, to catch this sorts of thing.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
it does -- and at the time of that PR it did

**Comment by davidchambers** [comment]
> it does

Where?

**Comment by buzzdecafe** [comment]
"All is well — The Travis CI build passed"

it's travis that runs the tests. i ran into the same thing with the `keys` refactor, which overlapped with the `++` changes. so i rebased and amended and all was well.

**Comment by davidchambers** [comment]
I'm suggesting that GitHub should *not* state "All is well" if merging a pull request will cause tests to fail. One shouldn't need to pull the branch, merge with master, and run the tests locally in order to know whether a pull request is fit to merge.

**Comment by buzzdecafe** [comment]
hmmm. on the `keys` one, it did *not* say that, it instead said something like "this cannot be automatically merged."

**Comment by davidchambers** [comment]
> hmmm. on the `keys` one, it did not say that, it instead said something like "this cannot be automatically merged."

Right, but that's something different. That's GitHub saying that there are merge conflicts which cannot be resolved automatically. I'm suggesting that Travis should simulate the merge and ensure that tests will also pass after merging.

**Comment by buzzdecafe** [comment]
i see. might be a bit of a tall order, since there are many events that might kick off a test suite.

**Comment by scott-christopher** [comment]
If you want to test post merge, you should just be able to update `.travis.yml` to something like:
```yaml
before_script:
- git pull origin master && make clean && make dist/ramda.js
```

**Pull request merged**
