### PR TITLE
@see annotations for head, tail, init and last family

### PR DESCRIPTION
**Pull request by kedashoe**
I knew ramda had `last` but wasn't sure what the complement was called. Figured nice to have links to the whole family

### CODE REVIEW

**Comment by davidchambers** [comment]
:deciduous_tree: Good idea!

**Comment by CrossEye** [comment]
Will JSDoc let us combine these into a single line?

```
/*
 * @see tail, init, last
 */
```

**Comment by kedashoe** [comment]
> Will JSDoc let us combine these into a single line?

I was going to write it like that but only saw the precedent in ramda for multiple lines

https://github.com/ramda/ramda/blob/master/src/transduce.js#L27-L40
https://github.com/ramda/ramda/blob/master/src/internal/_predicateWrap.js#L10-L11
https://github.com/ramda/ramda/blob/master/src/reduced.js#L13-L14

However, even if it did parse them as a single value, we would probably just need to do some pre-processing before outputting multiple links ala

https://github.com/ramda/ramda.github.io/pull/15

**Comment by CrossEye** [comment]
I haven't tried, but I would find it cleaner to have a single `@see` line in the source code.  If we don't have to do any mucking about with JSDoc to get it to work, I'd rather switch all occurrences of multiple `@see`s into combined lines.

It's not a big deal of course, either way.

**Comment by kedashoe** [comment]
> Will JSDoc let us combine these into a single line?

As I also think that is a nicer format, I've submitted a PR to ramdocs to handle this. I'll update this PR if you guys like/merge that one.

**Comment by CrossEye** [comment]
That one's been merged.

**Comment by kedashoe** [comment]
> That one's been merged.

Cool, shall I update all instances of multi-line `@see`s (there aren't that many), or just the ones currently in this PR?

**Comment by davidchambers** [comment]
My preference is to update the existing multi-line `@see`s in a separate pull request, merge that, then rebase this pull request. This will leave the clearest history. Does this work for you, @kedashoe?

**Comment by kedashoe** [comment]
ah, I was just working on this. Decided to update the others as there only two. I also fixed the [drop](http://ramdajs.com/docs/#drop) @see. I updated the commit message as well to note the additional multi-line @see fixes. Is this okay?

**Comment by davidchambers** [comment]
Looks good!

**Comment by CrossEye** [comment]
:herb:

**Pull request merged**
