### PR TITLE
Added addIndexRight

### PR DESCRIPTION
**Pull request by briancaine**
Implemented addIndexRight from #1898.

### CODE REVIEW

**Comment by CrossEye** [comment]
LGTM

**Review by CrossEye — APPROVED** [review]

**Comment by CrossEye** [comment]
@briancaine: as with many issues around this time, this PR was totally dropped.  Sorry about that.  We're getting around to addressing all these old issues, and just came across this one.

If you're interested in pursuing it, could you fix the conflict in `index.js`?  If not, feel free to close it.

**Comment by customcommander** [comment]
@CrossEye Rebased against master and fixed the conflicts. Will fail until #3224 is merged.

**Comment by customcommander** [comment]
@CrossEye Merge conflicts, lint and tests errors fixed. Good to go.

**Pull request merged**
