### PR TITLE
Move detailed spec to description section

### PR DESCRIPTION
**Pull request by kara-jovian**
The current description is quite confusing, I think it's better to use the comment from the `@return` section as a header because it's clear and complete.

### CODE REVIEW

**Review by CrossEye — CHANGES_REQUESTED** [review]
Welcome!  And thanks for the suggestion.

I agree that this is cleaner.  But perhaps after the 'Returns the first...` statement, we might add something like, "This function serves as the boolean `and` statement if both inputs are booleans."

Also, would you be willing to include a similar fix to the `or` function?

**Comment by karina-jovian** [comment]
>we might add something like, "This function serves as the boolean `and` statement if both inputs are booleans."

I guess it's a good idea, I'll make this amendment a bit later

>Also, would you be willing to include a similar fix to the or function?

Yes. Should I do this in this branch / PR or in a separate one?

**Comment by kara-jovian** [comment]
@CrossEye any updates?

**Review by CrossEye — APPROVED** [review]

**Comment by CrossEye** [comment]
Sorry for the delay.  Merged.

**Pull request merged**
