### PR TITLE
Update README with ng-ramda install instructions

### PR DESCRIPTION
**Pull request by JustinDFuller**
If you are interested, I've made a ng-ramda package that provides Ramda as an injectable Angular service.

### CODE REVIEW

**Comment by CrossEye** [comment]
I'm not sure whether this belongs in the ReadMe.  We'll have to think about that a bit.  But I'm definitely interested in seeing your package.  There's a long-abandoned one at https://github.com/ramda/ramdangular.

pinging @prathamesh7pute

**Comment by JustinDFuller** [comment]
@CrossEye Thanks for at least thinking about it. The reason I made this package is because ramdangular puts everything in the Angular root scope, which doesn't really fit in well with an Angular component architecture + dependency injections. It's essentially just crowding angular's "global" scope, which isn't very good to do.

**Comment by CrossEye** [comment]
I'm not really much of an Angular user.  Do I understand correctly that all your module does is to make Ramda something that can be injected into an Angular module?  Is there any advantage to that over importing it in your file?

I can certainly understand your objection to what Ramdangular does.  I spoke to the original author, and he doesn't really use it much himself either.  Ramda dropped the equivalent ability from its core some time ago.  But I'm not sure I understand what the advantage is to have Ramda, which should need no access to anything internal to your application, to be injected into your Angular modules.  What am I missing?

**Comment by buzzdecafe** [comment]
this would fit nicely in the [Related Projects](https://github.com/ramda/ramda/wiki) list, but I agree with @CrossEye probably not for the README

**Pull request closed without merging**
