### PR TITLE
rename R.nix

### LINKED ISSUE #929: rename R.nix
I'd prefer `R.complement`. Clojure uses this name: [`clojure.core/complement`][1]. The definition is apt:

> the members of a set or class that are not members of a given subset

Nix, on the other hand, means "nothing" or "cancel".

[1]: https://clojuredocs.org/clojure.core/complement

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #929

### CODE REVIEW

**Comment by buzzdecafe** [comment]
hmmm

```
Running "jshint:files" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.
```

**Comment by davidchambers** [comment]
```
~/github.com/ramda/ramda (complement)
$ PATH="/usr/local/n/versions/node/0.12.0/bin:$PATH" node -p 'require("path").basename(null)'
null

~/github.com/ramda/ramda (complement)
$ PATH="/usr/local/n/versions/io/1.6.0/bin:$PATH" node -p 'require("path").basename(null)'
path.js:8
    throw new TypeError('Path must be a string. Received ' +
          ^
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.basename (path.js:560:3)
    at [eval]:1:17
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:410:26)
    at evalScript (node.js:497:25)
    at startup (node.js:84:9)
    at node.js:866:3
```

**Comment by buzzdecafe** [comment]
https://github.com/iojs/io.js/pull/1153

**Comment by davidchambers** [comment]
We should lock down the io.js version in __.travis.yml__.

**Comment by buzzdecafe** [comment]
yes, and soon

**Comment by buzzdecafe** [comment]
https://github.com/ramda/ramda/pull/944

**Comment by buzzdecafe** [comment]
rebase to pick up my fix to .travis.yml and the build should pass

**Pull request merged**
