### PR TITLE
add "successor" property test for R.add

### PR DESCRIPTION
**Pull request by iamstarkov**
See more https://en.wikipedia.org/wiki/Addition#Successor

### CODE REVIEW

**Comment by davidchambers** [comment]
This property doesn't hold for `Infinity`, `-Infinity`, or `NaN`.

If you're in the mood you could submit a similar pull request for [`S.add`][1]: its stricter input type means the property should hold for all values in its domain.


[1]: https://sanctuary.js.org/#add

**Comment by iamstarkov** [comment]
`jsverify` disagrees with you, but okay

**Comment by CrossEye** [comment]
This will also fail with anything greater than `Number.MAX_SAFE_INTEGER`

That is, 

```js
Number.MAX_SAFE_INTEGER + 2 > Number.MAX_SAFE_INTEGER + 1 //=> false
```

**Comment by davidchambers** [comment]
Good point, Scott. This means that the property does not hold for `S.add` either.

**Pull request closed without merging**
