### PR TITLE
update .npmignore

### PR DESCRIPTION
**Pull request by davidchambers**
I think __/src/__ should be excluded as well. We needn't provide the source files in addition to the combined file.

### CODE REVIEW

**Comment by davidchambers** [comment]
I'll merge this then publish v0.10.0. We can discuss whether __/src/__ should be included in future releases.

**Comment by buzzdecafe** [comment]
:+1: on this pr, :-1: on including src/ in the distributed bundle

**Comment by davidchambers** [comment]
> :-1: on including src/ in the distributed bundle

It's currently included, so you're actually :+1: (as I am) on *excluding* __/src/__ from future tarballs.

**Comment by CrossEye** [comment]
:+1: on the :+1: disguised as a :-1:

**Comment by buzzdecafe** [comment]
:-1: on including == :+1: on excluding

no contradiction here

**Pull request merged**
