### PR TITLE
ramda@0.10.0

### PR DESCRIPTION
**Pull request by davidchambers**
This pull request updates Ramda's Ramda dependency. :)

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by CrossEye** [comment]
:sheep:

**Comment by buzzdecafe** [comment]
it's ramda's all the way down

**Comment by CrossEye** [comment]
:elephant: 
:turtle: 
:turtle: 
:turtle: 
:turtle: 
:turtle: 
:turtle: 
:turtle: 
.
.
.

**Pull request merged**
