### PR TITLE
Add transduce support for tap

### PR DESCRIPTION
**Pull request by wennergr**
Tap will act as tranducer if given a transformer in the second parameter

### CODE REVIEW

**Comment by buzzdecafe** [comment]
I can see how this would be very useful

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by lax4mike** [comment]
@wennergr This change breaks the following code:
```
R.compose(
  R.tap(console.log)
)(null)

// "Cannot read property '@@transducer/step' of null"
```

is this intended?

**Comment by CrossEye** [comment]
We really need to get a new release out.  This was fixed in 37da986.

**Pull request merged**
