### PR TITLE
Remove Object.prototype.toString.call from map

### PR DESCRIPTION
**Pull request by rtivital**
`R.type` provides same functionality

### CODE REVIEW

**Comment by davidchambers** [comment]
I'd prefer to limit the number of internal dependencies. This will be useful if and when "tree shaking" becomes possible.

**Comment by CrossEye** [comment]
> I'd prefer to limit the number of internal dependencies.

Agreed.

**Comment by davidchambers** [comment]
Thanks for the pull request nonetheless, @rtivital. :)

**Comment by buzzdecafe** [comment]
not reopening, but doesn't the dependency/tree-shaking argument cut both ways? i.e., if i include two functions and they both implement the same dependecnies themselves , haven't I duplicated the payload for no reason?

**Comment by davidchambers** [comment]
> haven't I duplicated the payload for no reason?

I'd expect no duplication after gzipping.

**Comment by buzzdecafe** [comment]
> I'd expect no duplication after gzipping.

doesn't that assume all the independent implementations are identical?

**Comment by davidchambers** [comment]
What is duplicated?

  - `Object.prototype.toString.call`
  - `[object `
  - `]`

That's all we'd avoid by using `R.type` here. These character sequences are bound to occur elsewhere, so will gzip very well.

**Comment by davidchambers** [comment]
I'm not sure we can generalize. For a non-trivial function I would favour reusing the Ramda function.

**Comment by CrossEye** [comment]
> I'm not sure we can generalize. For a non-trivial function I would favour reusing the Ramda function.

Although it's hard to quantify, I agree that this is the right standard.

**Comment by buzzdecafe** [comment]
I'll buy that

**Pull request closed without merging**
