### PR TITLE
revert change to R.propEq argument order

### LINKED ISSUE #1279: Revert change of propEq
I consider the changing of argument order in `propEq` to be a mistake. And it feels like an outcome of a misunderstanding of a [comment](https://github.com/ramda/ramda/pull/1243#issuecomment-119541173) I made. 

I noticed that there were some functions beginning with "prop" that took the prop name first and others that didn't. I didn't say this was a bad thing. I just wanted to highlight that it could be both and in the case of #1243 I thought it should be changed.

I do *not* feel that `propEq` should have the argument order changed. We use that function heavily and we sometimes only apply the first or just the first two arguments but we have *never* done `propEq(R.__, someValue)`. Now we would have to `propEq(R.__, 'someProp')` all over our code.

I vote to revert that change.

I also have some issues with how this was done, regardless of whether the change itself was good or not:
  * This change was merged in a PR unrelated to `propEq`
  * The change was not discussed
  * The PR was merged by the author

IMHO this is bad practice and I don't know if ramda has any guidelines for how to handle PRs but each of the items goes against what I find to be the purpose of PRs.

### PR DESCRIPTION
**Pull request by davidchambers**
Closes #1279

### CODE REVIEW

**Comment by CrossEye** [comment]
:herb:

**Comment by buzzdecafe** [comment]
:cow2:

look good to you, @TheLudd?

**Comment by TheLudd** [comment]
:horse:

**Comment by svozza** [comment]
Is there going to be a 0.16.1 release for this or will it be rolled up into 0.17?

**Comment by TheLudd** [comment]
I'd say `0.16.1` but it majes luttle dufference qhatever the choice is.

**Comment by davidchambers** [comment]
> Is there going to be a 0.16.1 release for this or will it be rolled up into 0.17?

I'll publish v0.17.0 today. This will be the only change in the release. I don't consider v0.16.1 appropriate for an API change: it would cause problems for those specifying `"0.16.x"` as the Ramda version in their __package.json__.

**Comment by asaf-romano** [comment]
Has the plan changed?

**Comment by davidchambers** [comment]
> Has the plan changed?

No. I didn't publish a new version on Friday as I said I would. Sorry about that. I've just done so. :)

**Pull request merged**
