### PR TITLE
Fix R.nth doc

### PR DESCRIPTION
**Pull request by fobos**
Fix arguments order in doc of R.nth

### CODE REVIEW

**Comment by davidchambers** [comment]
:deciduous_tree: Thank you, @fobos!

**Comment by buzzdecafe** [comment]
thanks -- not sure how that slipped past

**Comment by buzzdecafe** [comment]
curse you @davidchambers ! too fast for me again

**Comment by fobos** [comment]
@davidchambers @buzzdecafe  You are welcome, guys :) Let me know if I can help you somehow

**Pull request merged**
