### PR TITLE
Improve R.replace() documentation

### PR DESCRIPTION
**Pull request by foxbunny**
- Add a note about R.replace() delegating to String.prototype.replace()
- Change the signature to match actual behavior

(ref #2653)

### CODE REVIEW

**Comment by CrossEye** [comment]
I personally prefer the first commit.  I think it's simpler, and I really doubt we'd ever change this behavior.

I wouldn't even mind a version that read something like

     This function delegates to the `String.prototype.replace()`, so you could also supply
     a function as replacer.

or some such

**Comment by foxbunny** [comment]
It's getting a bit late in my neck of woods, so I'll redo the PR tomorrow.

**Comment by foxbunny** [comment]
I apologize for the delay. The PR has been updated.

**Comment by foxbunny** [comment]
I missed the point of the @CrossEye comment originally, so amended the last change. Sorry about the push spam. :)

**Comment by CrossEye** [comment]
Thank you for persevering.

**Pull request merged**
