### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by ivanzusko**
Hello, everyone!
I've started translating into the Ukrainian language. Hope you will accept it.

Cheers

### CODE REVIEW

**Comment by davidchambers** [comment]
Wonderful!

@ivanzusko, what is your plan for integrating changes from ramda/ramda into your fork?

**Comment by ivanzusko** [comment]
@davidchambers , thanx for a response! I hope to translate at least one chapter per week.
Is this okay?

**Comment by ivanzusko** [comment]
@davidchambers sorry was from iphone and it was a bit hard to give a descriptive answer.
As I do not have a cool domain name, I will just create a file, let's say `DOCUMENTATION.md` and then I'll but there method by method with translation. On top of the file will live all translated methods with anchor links to the translation below (something like Airbnb's [JS Style Guide](https://github.com/airbnb/javascript)).

**Comment by ivanzusko** [comment]
Yeah, but 200+ methods will be a pretty long list to scroll....

image

**Comment by ivanzusko** [comment]
> ntegrating changes from ramda/ramda into your fork
@davidchambers , finally get this question... I didn't think about that before. Any suggestions?(

**Comment by kedashoe** [comment]
> I didn't think about that before. Any suggestions?

cc @adispring .. any thoughts? How is your workflow going?

**Comment by adispring** [comment]
I make one directory([`i18`](https://github.com/ramdacn/ramda/tree/coding-pages/i18n)) which contains each api's different language comment, and checkout another branch(such as `coding-page`) for the translation。I also write some scripts to make translation more automatically. The detail procedure as follows: 

First procedure, In forked ramda repository:

1. In the forked repository, checkout branch master, pull newest original (ramda/ramda) master to current repo's master.
2. checkout branch `coding-page`(my translation branch), using script translate each src/api.js's comment from Chinese back to English, merge newest `master` to `coding-page`, solve conflict.
3. diff original ramda newest tag & last latest tag, update the changed part in forked repo's `i18n` dir.
4. using script translate each src/api.js's comment from English to Chinese.
5. do `npm run build`, output new dist/ramda.js & dist/ramda.min.js which will be used in forked  ramda.github.io for building ramda website page.

Second procedure, In forked ramda.github.io: 

1. using forked ramda repo's dist/ramda.js & dist/ramda.min.js and original ramda.github.io repo's newest code to build the webpage.

In the second procedure, there's more details have not said. I'll complete that when I have time.

Hope it might be of some help to you.

Chinese forked repos: https://github.com/ramdacn

**Comment by ivanzusko** [comment]
Thank you, @adispring, for such a detailed instruction! Hope I'll manage it :+1:

**Pull request merged**
