### PR TITLE
Updated ifElse docs.

### PR DESCRIPTION
**Pull request by jethrolarson**
Docs were misusing the word "predicate". I've updated them for clarity.

### CODE REVIEW

**Comment by davidchambers** [comment]
Could you run `make` to update __ramda.js__?

**Comment by jethrolarson** [comment]
Maybe later, I just updated via website, so I didn't have that handy.

**Comment by CrossEye** [comment]
I've dropped the ball on this, but I will try this weekend to see if we can get Travis to check back in the generated `ramda.js` on a successful build so that we can add this to `.gitignore` and not have to include artifacts of the build process in our commits.

**Comment by CrossEye** [comment]
Good catch on those changes.  That was definitely misuse of "predicate"!

**Pull request closed without merging**
