### PR TITLE
use `xs.push(x)` rather than `xs[xs.length] = x`

### PR DESCRIPTION
**Pull request by davidchambers**
We're currently mixing the two approaches. Let's stick with the more commonly seen `xs.push(x)`.

### CODE REVIEW

**Comment by davidchambers** [comment]
I'll merge this. If it turns out the other style is preferred, I'll open a pull request to use *that* consistently.

**Comment by buzzdecafe** [comment]
prefer the other way. i think this one should be reverted

**Comment by davidchambers** [comment]
> i think this one should be reverted

It wouldn't be a straight reversion, as we should commit to one approach or the other. If we prefer the other approach we should use it everywhere.

Why do you prefer `xs[xs.length] = x`?

**Comment by buzzdecafe** [comment]
this was a micro-optimization added way back. unless there is a compelling reason to undo those changes, i don't think we should

**Comment by davidchambers** [comment]
#890

**Pull request merged**
