### PR TITLE
hasPath return false for non-object checks

### PR DESCRIPTION
**Pull request by LorneCurrie**
Used to throw an Error for non-object children tests
Added test for object checking if val is an object when testing a path
Added tests testing false is returned for non-objects children tests
Related to GitHub issue #2771
Fixed based on the discussion in ticket

### CODE REVIEW

**Comment by Bradcomp** [comment]
Hi @LorneCurrie! Thanks for the PR! Are you sure this wasn't fixed [here](https://github.com/ramda/ramda/commit/4cd4e4bb85ab9d7a532fbb45e5e70009cdbc2098)? Does the test you wrote fail on master before your changes are applied?

If this still needs to happen, can you please fix the linting errors? You should be able to run the tests and linting locally before you push up.

Thanks again!

**Comment by LorneCurrie** [comment]
@Bradcomp No, I used the latest version of ramda and had an issue where I had an object to the below example.
```
import * as R from 'ramda';

const obj = {
  root: {
    foo: {
      bar: null,
      zar: {
        a: 'a',
        b: 'b',
      }
    }
  }
}

console.log(R.hasPath(['root', 'foo', 'bar', 'far', 'd'], obj));
```
I would have expected `false` to be returned.
`Error`:
```
xxx/node_modules/ramda/src/internal/_has.js:2
  return Object.prototype.hasOwnProperty.call(obj, prop);
                                         ^
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at _has (xxxpoc/node_modules/ramda/src/internal/_has.js:2:42)
    at hasPath (/xxxpoc/node_modules/ramda/src/hasPath.js:35:9)
    at Object.f2 [as hasPath] (/xxxpoc/node_modules/ramda/src/internal/_curry2.js:29:14)
    at Object.<anonymous> (/xxxpoc/fibre/client.ts:15:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module.m._compile (/home/lcurrie/.config/yarn/global/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/lcurrie/.config/yarn/global/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

**Comment by LorneCurrie** [comment]
Yea, I just looked at it again, and the fix you mentioned worked.  I have removed my change to the hasPath function but left my test cases in as I feel they are valid cases that would happen

**Comment by CrossEye** [comment]
I agree.  These look good.

**Pull request merged**
