### PR TITLE
adds-symbols - initial commit

### PR DESCRIPTION
**Pull request by thurt**
original issue: https://github.com/ramda/ramda/issues/1776

Also, here is a single file with all symbols together for easier viewing/editing: https://github.com/thurt/ramda-analysis/blob/master/symbols.js

There will be a second pull request to ramda.github.io repo in order to display these to the web documentation. I will reference it when I make that PR. 

This PR is totally flexible so add suggestions for the changes you would like to see!

### CODE REVIEW

**Comment by buzzdecafe** [comment]
this is really nice. thanks :cow2:

**Comment by CrossEye** [comment]
Very, very nice.  Thanks for all your hard work, and for putting up with my fiddling!

**Comment by CrossEye** [comment]
There's some issue that prevents this from automatically merging.  I'm still triaging issues that have come up over my vacation.  If no one has looked into it before I'm done with that, I'll try to figure it out.

**Comment by thurt** [comment]
I rebased this PR so you should be able to automatically merge now. The conflict was that `src/wrap.js` was deleted in a recent commit and I had a symbol added into that same file.

**Comment by buzzdecafe** [comment]
:tada:

**Comment by CrossEye** [comment]
This is great!  If we can find time, I'd love to publish a new point release just to include this on our site.

Thanks, @thurt!

**Pull request merged**
