### PR TITLE
Revert lift-based implementation of 'both' and 'either'

### LINKED ISSUE #1466: 0.18 regression: R.both does not short circuit
```js

R.both(R.complement(R.isNil), R.whereEq({ a: 1 }))(null)
// => 0.18: TypeError: n is null
// => 0.17: false
```

### PR DESCRIPTION
**Pull request by asaf-romano**
Closes #1466

### CODE REVIEW

**Comment by asaf-romano** [comment]
I had an interesting half an hour with git squash; had to kill the branch and start over.

**Comment by CrossEye** [comment]
:herb:

But also :cry: to see that elegant implementation not work for us.

@benperez: Any response to this?

**Comment by asaf-romano** [comment]
ping, pong.

**Comment by CrossEye** [comment]
Good point.

Any comments, @buzzdecafe, @davidchambers, @paldepind, @raine, @scott-christopher, @TheLudd?  Or again, @benperez?

**Comment by raine** [comment]
I am very happy to have the pre v0.18 behavior back.

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by scott-christopher** [comment]
:mushroom:

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by benperez** [comment]
@CrossEye Sorry for missing this one, I was out of the country for a while. Doesn't seem like there is any other way to get the short circuiting behavior in JS, although it is a bit of a shame.

**Comment by CrossEye** [comment]
I'm out of the country now.  ;-)

It really does seem a shame.  But we do stress that we won't let implementation elegance dictate our API.  I am sorry to see it go, though.

**Comment by benperez** [comment]
I thought about this today after a good night's sleep. The reason I preferred the lift based implementation wasn't just about implementation elegance, but rather that it was a better abstraction for what these functions are meant to do.

The current behavior of threading the results of applying 2 functions through `&&` and `||` is only one interpretation of lifted `&&` and `||` functions — for *functions* as applicative functors.

What's nice about the lift based implementations is that they actually work for *all* `fantasy-land` compatible applicative functors.
```javascript
> const R = require('ramda');
> const S = require('sanctuary');
> R.both(S.Nothing(), S.Just(true));     // => S.Nothing()
> R.either(S.Nothing(), S.Just(true));   // => S.Nothing()
> R.both(S.Just(false), S.Just(true));   // => S.Just(false)
> R.either(S.Just(false), S.Just(true)); // => S.Just(true)
```

Short circuiting is an important feature, and as was pointed out [here](https://github.com/ramda/ramda/issues/1466#issuecomment-151468622), it's not really possible to do in an eagerly evaluated language, unless we were to use something like a generator in the implementation of `liftN`, which I'm guessing is a non-starter.

Short circuiting only really seems important in the case of functions, since `Maybe`, `Either`, etc are just values already. I propose that we take the best of both worlds by special casing for functions in `R.both` and `R.either`
```javascript
R.both = _curry2(function both(f, g) {
  return f instanceof Function ?
    function _both() { return f.apply(this, arguments) && g.apply(this, arguments); } :
    lift(and)(f, g);
});
```

**Comment by davidchambers** [comment]
> I propose that we take the best of both worlds by special casing for functions in `R.both` and `R.either`

We can have our :cake: and eat it too? Sounds good!

**Comment by benperez** [comment]
@CrossEye I'll open a PR if there are no hesitations from you.

**Comment by CrossEye** [comment]
@benperez:

This sounds great.  I hadn't seen this side of it at all when you brought up the original implementation.  To me these simply _were_ operations on functions.  I like the higher abstraction a lot, though.

I haven't wrapped my head around _how_ they apply to arbitrary FL-compatible applicative functors.  I understood how our `and` and `or` once worked with Sanctuary's versions, but that was through delegation of these functions.

Definitely :+1: on a PR for this.

**Pull request merged**
