### PR TITLE
add R.dissoc

### PR DESCRIPTION
**Pull request by davidchambers**
The inverse of `R.assoc`; very similar to `R.omit`. See [`clojure.core/dissoc`][1].

[1]: http://clojuredocs.org/clojure.core/dissoc

### CODE REVIEW

**Comment by CrossEye** [comment]
Makes sense to me.   Of course we've got an issue open (#773) on slightly changing the behavior of `assoc` to work a bit more like `clone`; I'm not sure if it'll get approved.  @buzzdecafe is offering some stern (and reasonable) resistance.  But that behavior wouldn't make so much sense here, which might be the death-knell of that issue, I suppose.

But do we also want a `dissocPath` in parallel with `assocPath`?

    dissocPath('d.e', {a: 1: b: {c: 2}, d: {e: {f: 3, g: 4}, h: 5},i: 6});
    //=> {a: 1, b: {c: 2}, d: {h: 5}, i: 6}

? Or what I imagine will eventually be the API (#637), `dissocPath(['d', 'e'], obj)`?

**Comment by buzzdecafe** [comment]
`*socPath` have a nested-type problem, e.g.: `assocPath('a.b.1.c', 'moo', {a: b: [ {}, {c: 'cow'} ] }) //=> ???`

**Comment by buzzdecafe** [comment]
however, `dissoc` LGTM

:cake:

**Comment by CrossEye** [comment]
@buzzdecafe:

In the current version, it returns 

    {a: {b: {0: {}, 1: {c: 'moo'} } }})

If we follow through on #773, it should have:

    {a: {b: [ {}, {c: 'moo'} ] }})

At least that's what seems reasonable to me.

**Comment by davidchambers** [comment]
If there's consensus for this change, let's merge it and discuss `R.dissocPath` in a separate pull request.

**Comment by buzzdecafe** [comment]
agreed -- LGTM

**Pull request merged**
