### PR TITLE
introduce husky to guard ramda

### PR DESCRIPTION
**Pull request by adispring**
Run npm test and lint before git push.

### CODE REVIEW

**Comment by CrossEye** [comment]
That's probably a good idea.  I do it in all my work projects these days.

Any objections, @ramda/core?

**Comment by davidchambers** [comment]
I dislike commit hooks, but I have not committed to this project for a long time so don't mind me.

On an unrelated note, why do we include __package-lock.json__ in the repository? I've never seen a reason for libraries to include such files.

**Comment by GingerPlusPlus** [comment]
It's pre-push, not pre-commit.

👎 from me &ndash; this checks working directory, instead of commits that are about to be pushed.

About lockfile: https://github.com/ramda/ramda/pull/2625#issuecomment-412553820.

**Comment by adispring** [comment]
> 👎 from me – this checks working directory, instead of commits that are about to be pushed.

Using `lint-staged` , we can lint only changed files at commit stage, and only run unit test at push stage.

**Comment by GingerPlusPlus** [comment]
I wouldn't oppose `lint-staged`, even tho I'm not sure if it [properly](https://gist.github.com/luuuis/e41fd71134ce88ac5e9359cbdbfb6273) handles partial stages.

Naive `npm test` in `pre-push` disallows untracked files in `source/` and makes no sense when using `git push <remote> <branch>`. I don't know how to do this properly, I don't think this is the right place.

CI already lints and runs tests, correctly.

**Comment by adispring** [comment]
> Naive `npm test` in `pre-push` disallows untracked files in `source/` and makes no sense when using `git push <remote> <branch>`. I don't know how to do this properly, I don't think this is the right place.
> 
You can stash the untracked files before push. 

Run lint and unit test locally can find some obvious errors earlier, maybe this can save some time than remote CI.

**Comment by GingerPlusPlus** [comment]
Hooks are supposed to enhance or ensure valid workflows, not break them.

**Pull request closed without merging**
