### PR TITLE
Add 'dispatches to transfomer objects' tests for find* functions

### PR DESCRIPTION
**Pull request by kurtmilam**
~Question: Do you prefer one PR per fn or should I batch them all into a single PR?~

Note: I'm not completely familiar with the transformer logic, so I have modeled the tests on other existing tests. Please take a look and let me know if I'm testing incorrectly.

Edit: Upon closer inspection, I realized that there are already transducer-related tests for these functions. With that in mind, I have edited the pull request title to reflect the new scope of this PR.

First mentioned here: https://github.com/ramda/ramda/issues/2346

### CODE REVIEW

**Comment by kurtmilam** [comment]
I updated the `can act as a transducer` test after realizing the first go wasn't testing what it claimed to be testing :S

**Comment by CrossEye** [comment]
I think it's fine that this one was by itself, but the others could certainly be batched together.

I have to get my head around transducers again before I can comment on the changes themselves.

**Comment by kedashoe** [comment]
Let's just do them all here in a single commit if it is all the same to you @kurtmilam

**Comment by kurtmilam** [comment]
Please see edited title and opening comment.

**Comment by kedashoe** [comment]
Looks good, can you resolve the conflicts @kurtmilam ?

**Comment by kurtmilam** [comment]
@kedashoe I believe this is all clear now.

**Comment by buzzdecafe** [comment]
:cow2:

**Pull request merged**
