### PR TITLE
fix insert.js typo

### PR DESCRIPTION
**Pull request by adispring**

### CODE REVIEW

**Comment by CrossEye** [comment]
I wonder if this should read "at position `index`".

**Comment by adispring** [comment]
at the/a specified/given index ?

**Comment by CrossEye** [comment]
"at the specified index" sounds fine to me.  The original used the name of a parameter, which we do occasionally, but I don't much like.  This is better.

**Comment by CrossEye** [comment]
Thank you.

**Comment by adispring** [comment]
😃

**Pull request merged**
