### PR TITLE
Make `R.split` work with arrays.

### LINKED ISSUE #2619: `R.split` should work on lists and not just strings
Does that seem reasonable? I am a little hesitant due to how weird strings are in JS with no underlying char class.

### PR DESCRIPTION
**Pull request by diasbruno**
Fixes #2619.

I wrote it with a `reduce` to allow other iterables to also work,
but it can be written to use the Iterable protocol.

Let me know if there is something to improve on this PR.

### CODE REVIEW

**Comment by diasbruno** [comment]
If this is going works with other iterables, the signature would be something like `a -> f a -> [f a]`. (?)

**Comment by CrossEye** [comment]
Just getting back to Ramda after some time away...

Could you provide some more context on *why* you want this?  Is it just that it seems a natural extension or did you have a real-world problem that would have been solved if only `split` also handled arrays?  How do you propose to handle the oddity that this would then accept a regex separator for strings, but not for arrays?

**Comment by diasbruno** [comment]
It's natural when we consider strings a list of chars, than it would be nice to allow it to work on any kind of list. 

One problem with this implementation is the idea that we need to check before execute the correct implementation (the regex case included). Maybe, it would be better to let `split` unchanged, since it's more connected to the String interface and make a new function to work with array.

**Comment by zacnomore** [comment]
I agree with separating this functionality from split, it would avoid confusion.

**Pull request closed without merging**
