### PR TITLE
adds description of expected function result

### PR DESCRIPTION
**Pull request by donnut**
I propose a more explicit description of the expected return value of the iterator function.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:+1: 

i believe the build is failing 'cuz we still require the built artifact to be checked in

**Comment by donnut** [comment]
Ah, that explains the error. Should I do something with this?

**Comment by buzzdecafe** [comment]
i think you can `git add dist/ramda.js`, then `git commit --amend` and then push.

**Comment by donnut** [comment]
Now I've ended up with two commits... Still looking for a 12 weeks MOOC on git basics, or just take time to RTFM.

**Comment by buzzdecafe** [comment]
i feel your pain. can you help out @davidchambers ? alternately you can just create a new branch and push a new PR from there. that may be simplest

**Comment by donnut** [comment]
I'll try to create a new branch.

**Pull request closed without merging**
