### PR TITLE
Fixed groupWith to pass adjacent elements to testing fn

### LINKED ISSUE #2012: Add groupByStreak - group values in a list by testing consecutive/adjasent values if they keep the steak going
I couldn't find anything like this in the docs, and implementation using simple re-combination of existing functions was not apparent either. 
As a side note, `R.groupWith` is *almost* that, except it does not pass adjacent items in the list, but rather tests against first item in the group against each next item. "fixing" `groupWith` changes semantic, so I propose a new function: `groupByStreak`

Especially useful to group records with dates into ranges.

Here is my implementation: 
```
const streak = (sameStreak) => {
  let s = 0
  let valueSet = false
  let lastVal = null
  return (v) => {
    if(!valueSet) {
      valueSet = true
      lastVal = v
      s = 0
    } else if(!sameStreak(lastVal,v)) {
      lastVal = v
      s += 1
    } else {
      lastVal = v
    }
    return s
  }
}
const groupByStreak = fn => R.compose(
  R.map(R.map(R.nth(1))),
  R.values,
  R.groupBy(R.nth(0)),
  R.converge(R.zip,[R.map(streak(fn)), R.identity])
)

const isConsecutive = (a, b) => a + 1 == b
groupByStreak(isConsecutive)([0,1,2,3,1,2,0,4,5,6,9]) // [[0, 1, 2, 3], [1, 2], [0], [4, 5, 6], [9]]
```

Would be happy to submit PR if the owners approve.

### PR DESCRIPTION
**Pull request by kmamykin**
Very minimal fix to the src code. Added docs and tests.

Fixes #2012

### CODE REVIEW

**Comment by CrossEye** [comment]
:herb:

**Comment by kedashoe** [comment]
:mans_shoe:

**Comment by CrossEye** [comment]
Any other feedback?

**Comment by kedashoe** [comment]
Anyone else? Are we good to merge this?

**Pull request merged**
