### PR TITLE
Fix memoize with more than 1 arguments

### PR DESCRIPTION
**Pull request by angeloocana**
After 0.24.0 calling memoize with 2 or more arguments stoped working.

issue: #2183

To fix it, we call **toString** with **arguments**.

### CODE REVIEW

**Comment by davidchambers** [comment]
Please remove __yarn.lock__ and revert all the formatting changes.

**Comment by angeloocana** [comment]
@davidchambers  vs code automatically added the spaces, now its fixed.

what about yarn.lock should I add it to .gitignore?

I saw a lot of projects with yarn.lock, this keeps everybody with same versions.

**Comment by davidchambers** [comment]
Please remove __yarn.lock__. It's useful for applications but doesn't make much sense for libraries.

**Comment by angeloocana** [comment]
ok

**Pull request closed without merging**
