### PR TITLE
once/docs: mention that first result is returned later

### PR DESCRIPTION
**Pull request by raine**

### CODE REVIEW

**Comment by CrossEye** [comment]
Anyone understand why this build is failing?  Travis seems to want to download the code from `ramda/ramda` rather than `raine/ramda` but I don't know why.

**Comment by scott-christopher** [comment]
It just looks like Travis tried running a build upon a new branch being pushed which was subsequently removed.

Judging by the [event log](https://api.github.com/repos/ramda/ramda/events) (IDs 3122679910 & 3122680145), I'm guessing @raine accidentally pushed this branch to `ramda/ramda` instead of his own fork.

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by raine** [comment]
> Judging by the event log (IDs 3122679910 & 3122680145), I'm guessing @raine accidentally pushed this branch to ramda/ramda instead of his own fork.

Yep, pushed to wrong remote by accident.

**Pull request merged**
