### PR TITLE
extract lensIndex test from lenses.js

### PR DESCRIPTION
**Pull request by DanH91**
Hi according to discussion [#1509](https://github.com/ramda/ramda/issues/1509) I made a lensIndes dedicated test file.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
i think this is already underway in https://github.com/ramda/ramda/pull/1510/files ?

**Comment by DanH91** [comment]
OK. Thanks. Do you have advice on where I should check to avoid dups efforts?

**Comment by buzzdecafe** [comment]
i don't know if there is a better way than scanning the issue/PR list.

**Comment by CrossEye** [comment]
But also note that #1509 has a section starting "This was referenced `n` days ago", with a pointer (now) to #1510 and this issue.  That's always one place to look.

**Comment by DanH91** [comment]
Ok. Thanks

**Comment by CrossEye** [comment]
@DanH91:

Thank you, in any case, for taking the time to work on this.  I'm sorry it was duplicated effort.  But we appreciate your help regardless.

**Pull request closed without merging**
