### PR TITLE
added test for fantasy-land/map test

### PR DESCRIPTION
**Pull request by ottonascarella**

### CODE REVIEW

**Comment by buzzdecafe** [comment]
LGTM

:cow2:

Thanks

**Comment by kedashoe** [comment]
Can we use the shared [Id](https://github.com/ramda/ramda/blob/master/test/shared/Id.js) for this test?

**Comment by kedashoe** [comment]
ping @ottonascarella .. would you like to update the pull request to use Id and squash your commits?

**Comment by kedashoe** [comment]
:+1:

**Pull request merged**
