### PR TITLE
Fix docs for startsWith and endsWith

### PR DESCRIPTION
**Pull request by plumdog**
- Fix the signatures
- Rewrite the docstring - hopefully to make it a bit clearer, and to mention that they works for strings too.

### CODE REVIEW

**Comment by CrossEye** [comment]
I don't have time tonight to dig into this.  I can't recall if this behavior on strings was intentional or simply fell out of the implementation.

If it's the latter, then we need to consider this a little more carefully.  My take is always that we document only intentional behavior.  If it's something that we didn't intend, we don't write tests for it, we don't document it, and we make no promises that it will survive in subsequent versions.

I'll try to look into it soon.

**Comment by asaf-romano** [comment]
Yes, it intentionally works for strings too.

**Comment by asaf-romano** [comment]
They were in fact the original use case, see https://github.com/ramda/ramda/issues/1842

**Comment by asaf-romano** [comment]
🌷

**Comment by mattgrande** [comment]
Strings was the original intent, but I included unit tests for both string and arrays, since all of the underlying functions that are used by this (`take` and `takeLast`) function on both.

See also: #2120

**Comment by CrossEye** [comment]
Thanks.  I thought I remembered something like that.

**Pull request merged**
