### PR TITLE
remove R.appendTo and R.prependTo

### PR DESCRIPTION
**Pull request by davidchambers**
These functions were added in #500 but are no longer necessary thanks to #819.

```javascript
// before           // after
R.appendTo(xs)      R.append(R.__, xs)
R.prependTo(xs)     R.prepend(R.__, xs)
```

### CODE REVIEW

**Comment by CrossEye** [comment]
:herb:

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by CrossEye** [comment]
Before we merge this, please see the discussion in #831.  Should we do further function removals/renames in two steps, with a version or two that simply add a deprecated tag to the documentation and changelog before we commit them?

**Comment by davidchambers** [comment]
I'd like to publish v0.12.0 this weekend (unless anyone objects) so people can start using transducers. I'd like to merge this pull request and the others which remove functions deprecated in v0.11.0. Does this sound reasonable?

**Comment by megawac** [comment]
I'd say do a pre-release

**Comment by CrossEye** [comment]
@davidchambers:does x.y.z give us a straightforward way to create _alpha_, _beta_, and _rc_ versions?   If so, then I like @megawac's suggestion.  If not, we really need to figure that out for our post-1.0 world, but I would be fine with releasing 0.12.0 sooner.

**Comment by davidchambers** [comment]
> does x.y.z give us a straightforward way to create _alpha_, _beta_, and _rc_ versions?

Not quite, at this stage. From the [source][1]:

    -i --increment <level>
            Specify the level of the current version number to increment.
            Valid levels: 'major', 'minor', 'patch', 'premajor', 'preminor',
            'prepatch', and 'prerelease'. 'patch' is assumed if this option
            is omitted.

We can do this:

```console
$ node_modules/xyz/node_modules/.bin/semver --increment preminor 0.11.0
0.12.0-0
```

But if we wish to use some prefix we'll need to specify `--preid`, which xyz does not currently support:

```console
$ node_modules/xyz/node_modules/.bin/semver --increment preminor --preid rc 0.11.0
0.12.0-rc.0
```

I'll update xyz and publish a version which supports `--preid`.

If we wish to publish prerelease versions we'll need to adopt the branching strategy outlined in https://github.com/ramda/ramda/issues/800#issuecomment-74550317 (or a similar strategy). This adds significant complexity.

@megawac and @CrossEye, what do you see as the benefits of prerelease versions?


[1]: https://github.com/davidchambers/xyz/blob/v0.5.0/xyz#L22-L26

**Comment by CrossEye** [comment]
> If we wish to publish prerelease versions we'll need to adopt the branching strategy outlined in https://github.com/ramda/ramda/issues/800#issuecomment-74550317 (or a similar strategy). This adds significant complexity.

I don't think we do.  My thought at least was that we would simply move at times from `x.y.z` to `x.(y+1).0-rc.0` and maybe to `-rc.1`, etc. before moving to `x.(y+1).0`.  If we need `alpha` or `beta` we could introduce those too, although I can't see that.

> @megawac and @CrossEye, what do you see as the benefits of prerelease versions?

My reason would be the way I and many others use such tools.  If I'm in a hurry for new features, I might take a beta or rc version and test it, but be ready to roll back because I know that there might be issues.  I don't expect those to be production-ready.  When I take a full `x.y.z` version, I expect the kinks have been worked out.  Publishing something with as dramatic changes as the transducers fix would be a good candidate for such a release.  Honestly if I'd thought about it, the `_curry` changes were probably also in that category.

**Pull request merged**
