### PR TITLE
isTruthy - isFalsy

### PR DESCRIPTION
**Pull request by thefourtheye**
Introducing `isTruthy` and `isFalsy`

This are simple helper functions which will come in handy to test if
the given value is Truthy or Falsy.

### CODE REVIEW

**Comment by davidchambers** [comment]
Thanks for the pull request. I don't think these functions are necessary, though.

```javascript
R.isTruthy ≍ Boolean
R.isFalsy  ≍ R.complement(Boolean)
```

**Comment by thefourtheye** [comment]
Oh. Is there any function which is equivalent to `isTruthy`? I wanted to filter out a list of Truthy items from a list. But I couldn't find the proper filter function.

**Comment by davidchambers** [comment]
```javascript
> R.filter(Boolean, ['', 'x', 0, 1])
[ 'x', 1 ]
> R.reject(Boolean, ['', 'x', 0, 1])
[ '', 0 ]
```

**Comment by thefourtheye** [comment]
@davidchambers Ah, `Boolean`. Thanks :-)

**Comment by davidchambers** [comment]
No problem. :)

**Comment by thefourtheye** [comment]
@davidchambers I was using `R.identity` along with `Array.prototype.filter`, and it was working fine. I think for the `filter` case that also should be enough :-)

**Comment by davidchambers** [comment]
I like to use `Boolean` rather than `R.identity` because it matches the type "required" by `R.filter`:

    R.filter :: (a -> Boolean) -> [a] -> [a]

`R.identity` works equally well, but I like to avoid implicit type coercion.

**Pull request closed without merging**
