### PR TITLE
[CI] Drop support for Node older than 8.x

### PR DESCRIPTION
**Pull request by GingerPlusPlus**

### CODE REVIEW

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by mattgrande** [comment]
It looks like Node 8 is still in Active support until April 2019; Why would you want to remove it from CIs now?

https://github.com/nodejs/Release

**Comment by GingerPlusPlus** [comment]
@mattgrande I didn't remove Node 8.

**Comment by mattgrande** [comment]
Ugh, sorry, I read "older than 8.x" in the title and read it as "get rid of 8.x." Ignore me :)

**Comment by CrossEye** [comment]
:herb:

Any objections, @ramda/core ?

**Comment by davidchambers** [comment]
Do we have browser tests? If not, testing against old versions of Node seems like a good idea.

**Comment by Bradcomp** [comment]
I too am hesitant to remove old node tests without browser tests, as they serve as a mediocre proxy for that. I also don't think we should remove Node 6 until it's off LTS. Somebody should look into getting browser tests set up though so that we can get rid of older node versions without worry.

I think it would behoove us to determine what browsers and environments we want to support and then document that.

**Comment by buzzdecafe** [comment]
> Somebody should look into getting browser tests set up

NOT IT

**Comment by GingerPlusPlus** [comment]
Please review #2599, in which I fixed browser tests.

**Comment by GingerPlusPlus** [comment]
Can this be merged, now that browser tests are up?

**Comment by Bradcomp** [comment]
So we aren't supporting maintenance LTS now, only active?

**Comment by GingerPlusPlus** [comment]
Yes.

**Comment by Bradcomp** [comment]
I think that's really problematic. Browsers are weird in that we don't know how long they have to be supported, so it makes sense to determine an arbitrary cut off. With Node, we have a clear roadmap for what versions are supported and when they die. 

It's really straightforward to know which versions of Node are currently supported. That includes The most recent, the active LTS, and the maintenance LTS. I see no reason we shouldn't support all three.

**Pull request merged**
