### PR TITLE
MIT Licensing updates

### PR DESCRIPTION
**Pull request by MarcBalaban**
Was updating our company docs for our legal purposes and noticed Ramda was a little out of date.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
thanks! we should probably add some other names in there as well, but that's another pr

**Comment by CrossEye** [comment]
Yes, but there are enough people that perhaps we should find a generic phrase.  IANAL.  Does anyone know if something as abstract as "Copyright (c) 2013-2016 The contributors to https://github.com/ramda/ramda" would pass legal muster?

**Comment by buzzdecafe** [comment]
@CrossEye that's exactly why i wanted to merge this one quickly :-)

**Comment by CrossEye** [comment]
Absolutely.  I agree.  But if nothing else there's at least one more name that should be on that list.  I would love to make it more generic...

And I just don't care that much.

**Comment by davidchambers** [comment]
We could add this line:

    Copyright (c) 2016 Ramda

I don't know whether this is completely valid, but it's the approach I'm taking with Sanctuary.

**Comment by jackfirth** [comment]
**I am not a lawyer and you should get a lawyer to look into this**

The name used in the license should be the "entity that owns the copyright". In the case of a Github project with multiple contributors, that would be a list of the full names of everyone who ever submitted a pull request. Using "Ramda" would imply that "Ramda" refers to a legal entity, such as a corporation or nonprofit.

**Pull request merged**
