### PR TITLE
rename isSet to allUniq

### LINKED ISSUE #1278: Rename isSet
isSet naming is too confusing, imo. My first guess would be that it is either ```has``` or ```is(Set)```.

### PR DESCRIPTION
**Pull request by asaf-romano**
Closes #1278

### CODE REVIEW

**Comment by davidchambers** [comment]
Perhaps this pull request should add `R.allUniq` and deprecate `R.isSet` (rather than remove it).

**Comment by TheLudd** [comment]
@davidchambers good catch =)

**Comment by davidchambers** [comment]
@asaf-romano, would you like to update this pull request?

**Comment by asaf-romano** [comment]
will do.

**Comment by davidchambers** [comment]
It would have been nice to update this pull request rather than open a new one.

**Pull request closed without merging**
