### PR TITLE
fix typo in `dropRepeatsWith`'s documentation

### PR DESCRIPTION
**Pull request by benjycui**
It seems that it is a typo, but I am not sure :-)

### CODE REVIEW

**Comment by CrossEye** [comment]
Actually, I don't think this is a typo.

I'm not sure we've got a great syntax for this yet (see #1554) but the predicate supplied here is never going to be treated as a curried function, even if you supply one that happens to be curried.  It will always be called with two parameters.

**Comment by buzzdecafe** [comment]
if it's not a typo, it's still not correct:

`@sig (a, a -> Boolean) -> [a] -> [a]`

should be

`@sig ((a, a) -> Boolean) -> [a] -> [a]`

**Comment by CrossEye** [comment]
That's why I brought up #1554.  There is some debate about how we should represent pairs/tuples in these signatures.  But certainly we need something to group them, or there's no way to distinguish between `((a, a) -> Boolean)` and `(a, (a -> Boolean))`.

**Comment by CrossEye** [comment]
But agreed we should fix this, and probably to the version @buzzdecafe suggests.

**Comment by niloy** [comment]
`a * a` is used to represent tuple in F#.

https://en.wikipedia.org/wiki/Product_type

**Comment by buzzdecafe** [comment]
> a * a is used to represent tuple in F#.

right, that traces its ancestry to ML. Unfortunately, I don't think it fits in this case, because we are just trying to indicate that the function takes two arguments, but may or may not be curried. And it does not *really* take a tuple for an argument.

**Pull request closed without merging**
