### PR TITLE
Remove duplicate test cases

### PR DESCRIPTION
**Pull request by mapkts**

### CODE REVIEW

**Comment by mapkts** [comment]
I'm a newbie to functional programming and recently I notice something weird to me when looking into Ramda source code. Some methods of Ramda seem not favour pointfree style, like gt, substract and concat. The argument order of concat I expected is concat(what, data), but Ramda's implementation is more likely to be translated as "a concat b". When using Ramda's concat in partially application or function pipeline, we write code like:
```javascript
const concatRamda = flip(concat('ramda'))
compose(toUpperCase, concatRamda)('enter ') //=> 'ENTER RAMDA'
```
In my opinion concat(what, data) is more nature and intutive. We does not need to introduce extra flip and it's more consistent with the remaining codebase. Does Ramda design these methods for a reason?

**Comment by CrossEye** [comment]
I can't tell whether you think these tests should be removed because you think the API should change or if you see real duplication in the tests as your issue title implies.  If the latter, what do you see duplicated?

As to this:

> Does Ramda design these methods for a reason?

I'm just going to repost part of my answer from https://github.com/ramda/ramda/issues/2895#issuecomment-536237789:

>> BTW it's strange to see that R.gt and R.lt using first argument as value.

> You're asking about things that have a long history of controversy in Ramda.  I'm afraid I don't have the strength to look up the references, as I will start re-reading all our old arguments and tedious discussions about them.  But if you search for "operator", you will find at least a dozen issues related to this.
> 
> Briefly, there is a serious tension between, for instance,
> 
> ```
> R.subtract(10, 3) //=> clearly should be 7
> ```
> 
> and 
> 
> ```
> const less3 = R.subtract(3)
> 
> less3(10) //=> we want this to be 7, but it's -7.
> ```
> 
> This is true for `gt` as well, and for any binary operator where `op(a, b) !== op(b, a)`.  We have never really found a solution we liked for this.

**Comment by mapkts** [comment]
Sorry I didn't provide enough imformation about this PR. There is real duplication in the test:
```javascript
  it('adds combines the elements of the two lists', function() {
    eq(R.concat(['a', 'b'], ['c', 'd']), ['a', 'b', 'c', 'd']);
    eq(R.concat([], ['c', 'd']), ['c', 'd']);
  });

  var z1 = {
    x: 'z1',
    concat: function(that) { return this.x + ' ' + that.x; }
  };
  var z2 = {
    x: 'z2'
  };

  it('adds combines the elements of the two lists', function() {
    eq(R.concat(['a', 'b'], ['c', 'd']), ['a', 'b', 'c', 'd']);
    eq(R.concat([], ['c', 'd']), ['c', 'd']);
  });
```
Now it's obvious I supposed.

**Comment by CrossEye** [comment]
Weird, I swear I looked at the file and didn't see it.  I must have looked at the one from your commit...

Thank you.  This is clearly needed.

**Pull request merged**
