### PR TITLE
deprecate R.get

### PR DESCRIPTION
**Pull request by davidchambers**
Related to #867

### CODE REVIEW

**Comment by buzzdecafe** [comment]
should we list what version we expect it to be removed in?

**Comment by davidchambers** [comment]
> should we list what version we expect it to be removed in?

I'd prefer not to be tied to a particular version.

I think deprecated functions should only stick around for one minor version. It's important that we continue to progress towards 1.0.0.

**Comment by buzzdecafe** [comment]
:cow2:

**Comment by CrossEye** [comment]
:herb:

**Pull request merged**
