### PR TITLE
Document R.ap as S Combinator

### PR DESCRIPTION
**Pull request by MikaAK**
Ramda `ap` function can be used as S Combinator but I found no reference to it anywhere

``` javascript
R.ap(R.add, R.inc)(100) === R.add(100, R.inc(100))
```

### CODE REVIEW

**Comment by davidchambers** [comment]
```haskell
ap :: Apply f => f (a -> b) -> f a -> f b
```

Replace `Apply f => f` with `Function x`:

```haskell
ap :: Function x (a -> b) -> Function x a -> Function x b
```

Use `* -> *` sugar for `Function * *`:

```haskell
ap :: (x -> a -> b) -> (x -> a) -> (x -> b)
```

Rename type variables:

```haskell
ap :: (a -> b -> c) -> (a -> b) -> (a -> c)
```

The Function-specific signature, like the Array-specific signature, is a clearer but less precise type signature. My preference is for each function to have one (canonical) signature, and for the usage examples to indicate how it applies to different types.

**Comment by buzzdecafe** [comment]
@davidchambers so if @MikaAK removes the function-specific `@sig` from the pr, would you be in favor of merging? That is, just the example text? i would. :cow2:

**Comment by davidchambers** [comment]
I would, but we can do better than `R.ap(R.add, R.inc)(5)`. The problem with this example is that `R.add` is commutative, so the order in which the arguments are provided is unclear. I'd prefer to see `R.ap(R.concat, R.toUpper)('Ramda')`.

**Comment by buzzdecafe** [comment]
> `R.ap(R.concat, R.toUpper)('Ramda')`

Nice example! :wink: I'll buy that.  @MikaAK are you willing to make these changes, please?

**Comment by MikaAK** [comment]
Sure will do when I get a quick sec!

**Comment by MikaAK** [comment]
Moved to #2174 @davidchambers

**Pull request closed without merging**
