### PR TITLE
define R.partition without _reduce

### PR DESCRIPTION
**Pull request by davidchambers**

### CODE REVIEW

**Comment by megawac** [comment]
Worth doing something like https://github.com/jashkenas/underscore/issues/1594?

**Comment by davidchambers** [comment]
I'm keen to remove an internal dependency, not replace one with another. ;)

**Comment by megawac** [comment]
Eh, in my opinion composition makes sense for groupBy, partition, countBy,
and index?By as they use the same code (this would also allow them to
potentially be implemented via a transducer)

**Comment by buzzdecafe** [comment]
i should compile a list of remaining functions that should be transducerified.

**Comment by davidchambers** [comment]
((:bell:)) @CrossEye

**Comment by CrossEye** [comment]
Guess I missed this one.   I have the same feeling about this as about the other related ones.   I mostly take issue with the motivation behind it.  There's nothing wrong with the code, or with making the change.   But as you pointed out in another thread, we need to determine how we weigh the competing priorities.

**Pull request closed without merging**
