### PR TITLE
add support for io.js

### PR DESCRIPTION
**Pull request by honzabrecka**
Do we want to support io.js? A few tests are failing.

### CODE REVIEW

**Comment by buzzdecafe** [comment]
i think we should support IO. which tests are failing?

**Comment by honzabrecka** [comment]
`invert` and `invertObj`

I'll check it why it happens.

**Comment by buzzdecafe** [comment]
looks like it is failing on the "throws on zero args" test

**Comment by honzabrecka** [comment]
`assert.throws` should be used as follows:

```
assert.throws(function() { R.invert(1); });
```

but the problem is, that neither `R.invert(1)` and `R.invert(null)` throw an error, it always return `{}` for those special cases.

So each test should check if result is `typeof result == 'object'`.

**Comment by buzzdecafe** [comment]
IMO `R.invert(1)` and `R.invert(null)` *should* throw an error. So the test is correct. I wonder why it fails on one platform but not the other

**Comment by honzabrecka** [comment]
For me it do not throw an error on any platform, it returns an `{}`.

**Comment by buzzdecafe** [comment]
hmmm. then how did those tests *ever* pass?

```
        assert.throws(R.invertObj(1));
        assert.throws(R.invertObj('1'));
        assert.throws(R.invertObj(null));
        assert.throws(R.invertObj(undefined));
 
```

**Comment by honzabrecka** [comment]
Look at http://nodejs.org/api/assert.html#assert_assert_throws_block_error_message. io.js has better error messages and is more strict, so it expects function as assert.throws first argument.

The `assert.throws(R.invertObj(1))` haven't ever worked, because `R.invertObj(1)` is simply evaluated before the assertion. This is how `assert.throws` works inside:

```
assert.throws = function(f) {
  try {
    f();
    assert.fail('expected error');
  } catch (error) {}
}
```

**Comment by buzzdecafe** [comment]
yes, gotta wrap those tests in lambdas. thanks for catching this

**Comment by honzabrecka** [comment]
I'm curious if that tests will pass. :)

**Comment by buzzdecafe** [comment]
i doubt it, not without rewriting the source

**Comment by honzabrecka** [comment]
Updated to actual master.

**Comment by davidchambers** [comment]
:deciduous_tree: Thanks!

**Pull request merged**
