### PR TITLE
Add example of using a function with `type`

### PR DESCRIPTION
**Pull request by joaomilho**

### CODE REVIEW

**Comment by kedashoe** [comment]
:+1:

**Comment by buzzdecafe** [comment]
just got a linting error, otherwise looks good to me

:cow2:

**Comment by kedashoe** [comment]
looks like you have a trailing space on the line you added @joaomilho

**Comment by joaomilho** [comment]
Done. Goddamn, linting on comments, I wasn't even aware this was a thing!

**Pull request merged**
