### PR TITLE
Revert "R.uniq implementation to use Set if available"

### LINKED ISSUE #1188: R.uniq bug with Set
At the risk of being labeled [a concern troll](https://github.com/ramda/ramda/pull/907#issuecomment-111716832) I found that enviros w/o `Set`, e.g. IE 10 or Node 0.10:
```js
R.uniq([[1],[1]])
// => [[1]]
```

While enviros w/ `Set`, e.g. IE 11 or Node 0.12:
```js
R.uniq([[1],[1]])
// => [[1],[1]]
```

### PR DESCRIPTION
**Pull request by davidchambers**
Fixes #1188

### CODE REVIEW

**Comment by paldepind** [comment]
Yes. Appears to be the only solution given our definition of equality.

**Comment by scott-christopher** [comment]
It might be a good idea to add `[[1],[1]]` as a test for `uniq` here too.

**Comment by CrossEye** [comment]
:+1:

**Comment by davidchambers** [comment]
> It might be a good idea to add `[[1],[1]]` as a test for `uniq` here too.

Good idea. I have done so.

**Comment by buzzdecafe** [comment]
LGTM
:cow2:

**Pull request merged**
